### ISSUE TITLE
Support for Preact

### ISSUE THREAD

**Issue by ziongh** [farm-fe/farm#1006]
### What problem does this feature solve?

It would be awesome to support Preact.

### What does the proposed API look like?

We could create a @farmfe/plugin-preact package that does the work.

**Comment by wre232114** [comment]
It's awesome! PR welcome! thanks

**Comment by Maidang1** [comment]
> ### What problem does this feature solve?
> It would be awesome to support Preact.
> 
> ### What does the proposed API look like?
> We could create a @farmfe/plugin-preact package that does the work.

I've given it a try. The `@preact/preset-vite` works for Farm

**Comment by ErKeLost** [comment]
We are going to add a template for preact in the next version
