### ISSUE TITLE
a error ocurrs in farmfe/cli after update farm/core

### ISSUE THREAD

**Issue by sepZeng** [farm-fe/farm#1023]
### Steps to reproduce

file:///D:/farm-project/node_modules/@farmfe/cli/dist/utils.js:7
 import { DefaultLogger } from '@farmfe/core';

### What is expected?

file:///D:/farm-project/node_modules/@farmfe/cli/dist/utils.js:7
 import { DefaultLogger } from '@farmfe/core';

### What is actually happening?

file:///D:/farm-project/node_modules/@farmfe/cli/dist/utils.js:7
 import { DefaultLogger } from '@farmfe/core';

### System Info

```Shell
no
```

### Any additional comments?

no

**Comment by sepZeng** [comment]
"@farmfe/cli": "^0.6.2",
    "@farmfe/core": "^1.0.0", 
 Logger exported in @farmfe/core

**Comment by wre232114** [comment]
try `@farmfe/cli@1.0.0`
