### ISSUE TITLE
Not working with solid-router

### ISSUE THREAD

**Issue by AzurIce** [farm-fe/farm#1029]
### Steps to reproduce

1. Use `pnpm create farm` to create a solid project.
2. Update the dependency of solid-js by `pnpm update`
3. `pnpm i @solidjs/router`
4. Simply modify the index.tsx to do `render(() => <Router></Router>, root!)`

Here are my deps:
```
"@solidjs/router": "^0.13.0",
"solid-js": "^1.8.15"
```

### What is expected?

works fine

### What is actually happening?

not working, with following logs on browser console:
![image](https://github.com/farm-fe/farm/assets/22115534/2d0ce9eb-8dbe-43ce-bf3f-9d4aa544ba51)
it seems that the code isn't compiled correctly by vite-solid-plugin?
![image](https://github.com/farm-fe/farm/assets/22115534/0ef0a8ea-0d66-490a-a6e3-900b3221fdfb)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 1.90 GB / 15.93 GB
  Binaries:
    Node: 20.11.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.2.4 - ~\scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 8.3.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @farmfe/core: ^1.0.0 => 1.0.0
```
```


### Any additional comments?

_No response_

**Comment by wre232114** [comment]
I'll take a look. Thanks for reporting issues

**Comment by wre232114** [comment]
By default, Farm won't execute vite plugins for modules under node_modules. You should use following configs:

```ts
import { defineConfig } from "@farmfe/core";
import solid from "vite-plugin-solid";

export default defineConfig({
  vitePlugins: [() => ({
    vitePlugin: solid(),
    filters: [
      '\\.tsx$',
      '\\.jsx$',
    ] 
  })],
});
```
Then it would work fine. See [Function Syntax of Using Vite Plugins](https://farm-fe.github.io/docs/using-plugins#using-viterollupunplugin-plugins-in-farm) to learn more about configruing filters.

**Comment by AzurIce** [comment]
Thanks! It now works well!
