### ISSUE TITLE
@unocss/transformer-variant-group 无效

### ISSUE THREAD

**Issue by LiMao00** [farm-fe/farm#1053]
### Steps to reproduce

![e696c0e04bffc6934ac2579d253ec55](https://github.com/farm-fe/farm/assets/99939885/bec70ac0-8032-4b23-bac7-df1cd714240a)
![6323063921aac2d4afe121d6e1744f9](https://github.com/farm-fe/farm/assets/99939885/e186007b-07f1-4d2e-b91a-7dae86d6a403)

### What is expected?

可行

### What is actually happening?

无效

### System Info

```Shell
win10
chrome
```

**Comment by wre232114** [comment]
可以试试这个仓库 https://github.com/farm-fe/farm-soybean-admin ，加上 issue 里面的 transformer 看看效果

**Comment by callqh** [comment]
今天看了一下，因为farm中目前只能使用@unocss/postcss插件去应用unocss，目前该postcss插件功能有限，暂不支持transform的功能

**Comment by callqh** [comment]
@LiMao00 后续可以关注一下 #950
