### ISSUE TITLE
How to start the development environment?

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#107]
After installing the dependency, I want to try to start react demo in example, but I am not prompted by an error. How can I start it?
i have local rust environment. Do I need to do something?
> node 16.18.0

![image](https://user-images.githubusercontent.com/66500121/226781933-4afac326-4daa-4894-8a78-4508bc163a4e.png)

**Comment by wre232114** [comment]
Seems like you are building farm from source. You should execute `npm run build:rs` under `packages/core` to build a binary first.

**Comment by ErKeLost** [comment]
Thank you for your reply. I would like to join in and provide some pr

I tried to use `build: rs` in `package/ core`, but he didn't generate a dist file, and then I executed `pnpm start` to generate a dist directory,

And then I needed to build a package for cli and a package for plugin-react. 

When I thought it was done, its give me a error when I went to run react demo again. 

![image](https://user-images.githubusercontent.com/66500121/226793406-393d292e-fb51-4ffc-8b9d-facb8bec61a7.png)

![image](https://user-images.githubusercontent.com/66500121/226793465-e9df2ce6-dd7f-40db-8372-4350edf652e3.png)

I saw this bag is in a npm directory. Is there anything else I need to do?

**Comment by wre232114** [comment]
You should also execute `npm run build` under `rust-plugins/react` to build the react plugin

**Comment by wre232114** [comment]
I updated the `Contribution Section` of README, which misses the react plugin build step

**Comment by ErKeLost** [comment]
> I updated the `Contribution Section` of README, which misses the react plugin build step

Thank you. I'll try to see ， if I can assemble these into one command to facilitate development. I can mention a pr to do a scaffolding command.

**Comment by wre232114** [comment]
That would be really nice, thank you

**Comment by ErKeLost** [comment]
> Not for now, I will create one tonight

Okay, I'll be the first to add ，hah.

**Comment by wre232114** [comment]
Join the discord https://discord.gg/mDErq9aFnF. If you are interested in join Farm development, you can add my wechat `Bright980113`
