### ISSUE TITLE
打包之后css里的图片url没有包含publicPath

### ISSUE THREAD

**Issue by Weeken** [farm-fe/farm#1076]
### Steps to reproduce

![1711444697219](https://github.com/farm-fe/farm/assets/18238515/91c94a8f-769e-49dc-8758-16d648a40fa5)
![1711444778219](https://github.com/farm-fe/farm/assets/18238515/220229e2-6823-4904-a860-1d6441de9acb)

publicPath: '/front/page-recharge/'

打包之后的css
![1711444924345](https://github.com/farm-fe/farm/assets/18238515/f2353c76-0fbc-42c4-9fff-bc2d385dd266)
图片的url没有包含publicPath，导致上传服务器之后无法访问到

### What is expected?

打包的css图片url能包含publicPath

### What is actually happening?

![1711445086859](https://github.com/farm-fe/farm/assets/18238515/05a458e2-55ae-467d-9633-bc5bc5a3d2ee)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 3.26 GB / 15.75 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\fnm_multishells\7856_1711419260219\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\7856_1711419260219\yarn.CMD
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\7856_1711419260219\npm.CMD
    pnpm: 8.15.3 - ~\AppData\Local\fnm_multishells\7856_1711419260219\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @farmfe/core: ^1.0.6 => 1.0.6
```

**Comment by wre232114** [comment]
感谢反馈，我们马上修复
