### ISSUE TITLE
Can not load `node_modules/xxx/xx.vue`.

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1081]
### Steps to reproduce

use @vitejs/plugin-vue, My vue file is in node_modules. This error occurs in run dev

[ Farm ] Failed to start the server: Error: Can not load `node_modules/my-ui/src/components/button.vue`. Original error: 
None.

Potential Causes:
1.This kind of module is not supported, you may need plugins to support it.

    at logError (file:///E:/demo/test/node_modules/@farmfe/core/dist/server/error.js:59:11)
    at Server.compile (file:///E:/demo/test/node_modules/@farmfe/core/dist/server/index.js:60:29)
    at async Server.listen (file:///E:/demo/test/node_modules/@farmfe/core/dist/server/index.js:44:9)
    at async start (file:///E:/demo/test/node_modules/@farmfe/core/dist/index.js:32:9)
    at async handleAsyncOperationErrors (file:///E:/demo/test/node_modules/@farmfe/cli/dist/utils.js:111:9)

### What is expected?

Successful load vue file

### What is actually happening?

errorCannot start

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 11.19 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @farmfe/core: ^1.0.6 => 1.0.6
```

**Comment by wre232114** [comment]
modules under node_modules are not transformed by default, use `fileter functin synatx` to configure:

``` ts
// farm.config.ts
mport vue from '@vitejs/plugin-vue',

// Using function syntax of Vite plugin
function configureVitePluginVue() {
  // return plugin and its filters
  return {
    // using plugin vue
    vitePlugin: vue(),
    // configuring filters for it. Unmatched module paths will be skipped.
    filters: ['\\.vue$', '\\\\0.+']
  };
}

export default defineConfig({
  // configuring vite plugins
  vitePlugins: [
    configureVitePluginVue()
  ]
});
```

see https://www.farmfe.org/docs/using-plugins#using-viterollupunplugin-plugins-in-farm

**Comment by 289420843** [comment]
`import { defineConfig } from "@farmfe/core";
import Vue from "@vitejs/plugin-vue";

function configureVitePluginVue() {
  return {
    vitePlugin: Vue(),
    filters: ["\\.vue$", "\\\\0.+"],
  };
}

export default defineConfig({
  vitePlugins: [configureVitePluginVue()],
});`

[ Farm ] Using config file at E:\demo\test\farm.config.ts
[ Farm ] Failed to start the server: Error: Vite plugin [object Object] is not compatible with Farm for now. Because plugin name is required in Farm.
    at new VitePluginAdapter

**Comment by callqh** [comment]
> `import { defineConfig } from "@farmfe/core"; import Vue from "@vitejs/plugin-vue";
> 
> function configureVitePluginVue() { return { vitePlugin: Vue(), filters: ["\.vue$", "\\0.+"], }; }
> 
> export default defineConfig({ vitePlugins: [configureVitePluginVue()], });`
> 
> [ Farm ] Using config file at E:\demo\test\farm.config.ts [ Farm ] Failed to start the server: Error: Vite plugin [object Object] is not compatible with Farm for now. Because plugin name is required in Farm. at new VitePluginAdapter

I will fix this error.

**Comment by 289420843** [comment]
thank you.

**Comment by wre232114** [comment]
my mistake, try :

```ts
// Using function syntax of Vite plugin
function configureVitePluginVue() {
  // return plugin and its filters
  return {
    // using plugin vue
    vitePlugin: vue(),
    // configuring filters for it. Unmatched module paths will be skipped.
    filters: ['\\.vue$', '\\\\0.+']
  };
}

export default defineConfig({
  // configuring vite plugins
  vitePlugins: [
    configureVitePluginVue
  ]
});
```

**Comment by 289420843** [comment]
ok, success

**Comment by 289420843** [comment]
add the filters configuration, the error persists, you can try it

**Comment by 289420843** [comment]
> 添加过滤器配置后，错误是否仍然存在？`can not load xxx.vue`

yes

**Comment by wre232114** [comment]
we'll fix it today

**Comment by wre232114** [comment]
try `@farmfe/core@1.0.7`:
```ts
function configureVitePluginVue() {
  // return plugin and its filters
  return {
    // using plugin vue
    vitePlugin: vue(),
    // configuring filters for it. Unmatched module paths will be skipped.
    filters:  ["!node_modules", "node_modules/my-ui"]
  };
}
```

**Comment by joeyame** [comment]
To make this more searchable, here is how I applied this to svelte, and it works like a charm:

```Typescript
import { defineConfig } from '@farmfe/core'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import postcss from '@farmfe/js-plugin-postcss'

function configureSveltePlugin() {
  return {
    vitePlugin: svelte(),
    filters: ['\\.svelte$', '\\\\0.+'],
  }
}

export default defineConfig({
  plugins: [postcss()],
  vitePlugins: [
    configureSveltePlugin
  ],
})
```
