### ISSUE TITLE
修改publicDir不生效

### ISSUE THREAD

**Issue by Weeken** [farm-fe/farm#1095]
### Steps to reproduce

1、修改publicDir的值，打包的时候不生效
2、当html存在其他script标签时，打包没有加入publicPath

### What is expected?

1、修改publicDir能复制相应文件到相应的打包目录，不应只对根目录的public生效
2、对index.html里其他引用public的文件的script标签的src应该包含publicPath

### What is actually happening?

1、当根目录存在public文件夹时，打包之后能复制到对应的生成目录，但忽略了我修改的目录：
![1711704012659](https://github.com/farm-fe/farm/assets/18238515/c4a67425-24de-465c-a5b0-79263264936f)
2、当html存在其他script标签时，打包是否应该也要包含output.publicPath?
![1711704222196](https://github.com/farm-fe/farm/assets/18238515/f7a193f9-9aea-4884-867d-31eaf005a28a)
![1711704222204](https://github.com/farm-fe/farm/assets/18238515/97b7293f-83b4-4079-8fdf-8002983ad1c1)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 1.66 GB / 15.75 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\fnm_multishells\10472_1711683538335\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\10472_1711683538335\yarn.CMD
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\10472_1711683538335\npm.CMD
    pnpm: 8.15.3 - ~\AppData\Local\fnm_multishells\10472_1711683538335\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @farmfe/core: ^1.0.8 => 1.0.8
```

**Comment by wre232114** [comment]
我们看下

**Comment by ErKeLost** [comment]
fixed in 1.0.11

**Comment by callqh** [comment]
问题一已修复 #1105

**Comment by Weeken** [comment]
> 问题一已修复 #1105 ，可以尝试将包升级到[@farmfe/core@1.0.11](https://github.com/farm-fe/farm/releases/tag/%40farmfe%2Fcore%401.0.11)

好的
