### ISSUE TITLE
Not working with jsPDF (after build)

### ISSUE THREAD

**Issue by AndilibaZhu** [farm-fe/farm#1117]
### Steps to reproduce

i transfer project from vite to farm, it working nicely under vite.
Create new farm project
`yarn create farm // vue program`
`yarn add jspdf // version jspdf@2.5.1`
npm link [https://www.npmjs.com/package/jspdf](url)
code like this:
`import { jsPDF } from "jspdf";
const doc = new jsPDF();`
put at any page, it runs no problems under dev mode.
but if you `yarn build`,  the page can't open.
web browser err code:
`Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at oe (index_1d3b.aecb47d5.js:18700:32)
    at index_1d3b.aecb47d5.js:18706:16
    at e17eb7d5 (index_1d3b.aecb47d5.js:18712:6)
    at _.require (index.html:5:37090)
    at 87817ef5 (index_ec41.a0d71309.js:1:905)
    at _.require (index.html:5:37090)
    at badfa50a (index_ec41.a0d71309.js:1:3550)
    at _.require (index.html:5:37090)
    at 89380c7c (index_ec41.a0d71309.js:1:2267)
    at _.require (index.html:5:37090)
`
my testing page like this:
<img width="801" alt="image" src="https://github.com/farm-fe/farm/assets/107983218/519185f2-8abf-4bd2-b757-3589b5ac2ff8">

### What is expected?

work normally

### What is actually happening?

the page down.

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 109.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    bun: 1.0.20 - ~/.bun/bin/bun
  Browsers:
    Edge: 123.0.2420.53
    Safari: 17.3
```

**Comment by wre232114** [comment]
I'll take a look
