### ISSUE TITLE
refactor: `@farmfe/cli`

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#1123]
### What problem does this feature solve?

Use more modern tools to optimize farm cli functionality as well as functional programming and performance issues

1. Use [`citty` ](https://github.com/unjs/citty) rewrite cli
2. Split functional structure `watch` , `build`, `start`, `preview`, `clean` command
3. Rewrite cli with more elegant functional programming

### What does the proposed API look like?

detail see [citty](https://github.com/unjs/citty/tree/main/playground)

**Comment by fu050409** [comment]
Working on this issue
