### ISSUE TITLE
Too strict html parsing.

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1136]
### Steps to reproduce

Have a html that has templating stuff in it for ssr:

```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {head}
    {styles}
  </head>
  <body>
    <div id="app">{ssr}</div>
    <script type="module" src="./src/main.ts"></script>
  </body>
</html>

```

### What is expected?

Those are considered as text and ignored like vite does (I'm moving this project from vite to farm as it looks more concise, managed and progressive).

### What is actually happening?

The parser got scrambled and throws:

![image](https://github.com/farm-fe/farm/assets/7501201/ea0e9bd4-77ed-4e57-ae34-1ec264ab5c25)

### System Info

```Shell
Win10x64 Pro latest, Intel 14600kf, 32Gb ram, almost empty.
```

### Any additional comments?

If you have any preffered workaround for this case, please tell me.

**Comment by wre232114** [comment]
Thanks for reporting issues. I'll make it less strict today and release `@farmfe/core@1.0.15`. For earlier versions, you can use html tags as placeholders like:

```html
<div id="root">
  <div>app-html-to-replace</div>
</div>
```

**Comment by wre232114** [comment]
please try `@farmfe/core@1.0.15`

**Comment by houd1ni** [comment]
```
 > npm i @farmfe/core@1.0.15


added 1 package, removed 1 package, changed 1 package, and audited 806 packages in 10s

190 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

```
> npm run d-dev

> menu-front@0.0.1 dasha-dev
> farm start ./d-c ./.../farm.config.ts

[ Farm ] Using config file at C:\Users\...farm.config.ts
[ Farm ] Port 9000 is in use, trying another one...
[ Farm ] Port 9001 is in use, trying another one...
[ building ] ⠂ transform (15) ../node_modules/@farmfe/runtime-plugin-hmr/src/overlay.ts.farm-runtime                                         [ Farm ] Failed to start the server: Error: Parse `index.html` failed.
 Error: Parse `index.html` failed.
 Error:
  × Stray end tag "head"
   ╭─[index.html:4:1]
 4 │     <meta charset="utf-8" />
 5 │     {head}
 6 │     {styles}
 7 │   </head>
   ·   ───────
 8 │   <body>
 9 │     <div id="app">{ssr}</div>
 9 │     <script type="module" src="./src/main.ts"></script>
   ╰────

  × Start tag "body" seen but an element of the same type was already open
    ╭─[index.html:5:1]
  5 │     {head}
  6 │     {styles}
  7 │   </head>
  8 │   <body>
    ·   ──────
  9 │     <div id="app">{ssr}</div>
 10 │     <script type="module" src="./src/main.ts"></script>
 10 │   </body>
    ╰────

```

**Comment by wre232114** [comment]
It works in our example: https://github.com/farm-fe/farm/blob/main/examples/react-ssr/index.html#L10

**Comment by houd1ni** [comment]
> It works in our example: https://github.com/farm-fe/farm/blob/main/examples/react-ssr/index.html#L10

Yep, but not in <head>

**Comment by wre232114** [comment]
It's limited by SWC, you may have to use other placeholders like `<meta head />`, `<meta styles />` in `<head>`.

**Comment by houd1ni** [comment]
So sad. Thank you anyway, - I'll try.

**Comment by houd1ni** [comment]
@wre232114 wait a sec, - can I write a plugin to clean the input for dev-hmr process ?https://www.farmfe.org/docs/plugins/writing-plugins/js-plugin

**Comment by houd1ni** [comment]
I've tried to workaround this by using the plugin system to avoid changing backend logic, but got an error.

I want to transform it to meta stuff you've suggested, then in the very end reverse those.



What I do:
![image](https://github.com/farm-fe/farm/assets/7501201/7beef259-67f5-455f-a333-6b006bfa5045)

What I get using almost the sample code https://www.farmfe.org/docs/api/js-plugin-api#transformhtml :
![image](https://github.com/farm-fe/farm/assets/7501201/3d70e63c-a86a-4c9f-9d5c-92206d3d85ce)

**Comment by wre232114** [comment]
make `transformIndex` async:

```ts

**Comment by houd1ni** [comment]
The change
![image](https://github.com/farm-fe/farm/assets/7501201/af54c5dd-9bc0-495c-bf28-4fa3e7419712)

results in
![image](https://github.com/farm-fe/farm/assets/7501201/e1e45a6c-262a-4fb9-b23b-df816231a7c0)

**Comment by wre232114** [comment]
I tested that this should work:

```js
[
      {
        name: 'test-transform-html-pre',
        transformHtml: {
          order: 0, // 0 means call this hook before parse and generate resources
          executor: async ({ htmlResource }) => {
            const code = Buffer.from(htmlResource.bytes as any).toString();
            calledHooks.push('transformHtmlPre');
            const replacedCode = code
              .replace('{head}', '<meta head />')
              .replace('{style}', '<meta style />')
              .replace('{ssr}', '<meta ssr />');
            return {
              ...htmlResource,
              bytes: [...Buffer.from(replacedCode)]
            };
          }
        }
      },
      {
        name: 'test-transform-html-post',
        transformHtml: {
          order: 2, // 2 means call this hook after parse and generate resources
          executor: async ({ htmlResource }) => {
            calledHooks.push('transformHtmlPost');
            const replacedCode = Buffer.from(htmlResource.bytes as any)
              .toString()
              .replace(/<meta (\w+?)>/g, '{$1}');
            htmlResource.bytes = [...Buffer.from(replacedCode)];
            return htmlResource;
          }
        }
      }
    ]
```

**Comment by houd1ni** [comment]
Yep. I've rewrite it to match codestyle and removed calledHooks tracing. It compiles, but breaks the runtime: it throws, telling, that one of my library functions is not a function. It should be interesting in the compiler perspective and to improve docs, but I'd rather stick with <meta /> stuff, 'cause it now looks more safe 😄 Here's code btw:

```typescript
plugins: [
    {
      name: '[test-transform-html-pre]',
      transformHtml: {
        order: 0, // 0 means call this hook before parse and generate resources
        executor: async ({ htmlResource }) => {
          htmlResource.bytes = [...Buffer.from(Buffer
            .from(htmlResource.bytes as any)
            .toString()
            .replace('{head}', '<meta head />')
            .replace('{styles}', '<meta style />')
            .replace('{ssr}', '<meta ssr />')
          )]
          return htmlResource
        }
      }
    },
    {
      name: '[test-transform-html-post]',
      transformHtml: {
        order: 2, // 2 means call this hook after parse and generate resources
        executor: async ({ htmlResource }) => {
          htmlResource.bytes = [...Buffer.from(Buffer
            .from(htmlResource.bytes as any)
            .toString()
            .replace(/<meta (\w+?) \/>/g, '{$1}')
          )]
          return htmlResource
        }
      }
    }
  ]
```

**Comment by wre232114** [comment]
> It compiles, but breaks the runtime: it throws, telling, that one of my library functions is not a function.

Could you please provide more info about the runtime error

**Comment by houd1ni** [comment]
> > It compiles, but breaks the runtime: it throws, telling, that one of my library functions is not a function.
> 
> Could you please provide more info about the runtime error

![image](https://github.com/farm-fe/farm/assets/7501201/3011bd47-54d5-4a76-85a4-83dbab86a4d4)
it's from fela-vue precompressed library.
![image](https://github.com/farm-fe/farm/assets/7501201/0ba1c46c-8498-44d1-93aa-f56f61daf86a)
The line from stack trace highlighted by blue.
![image](https://github.com/farm-fe/farm/assets/7501201/66d0d192-4f55-4984-8255-41192a1542fd)
And then it traces up to the application code.

And no such error with vite or without the transformations.

Just in case, the error look in chrome:
![image](https://github.com/farm-fe/farm/assets/7501201/954d647f-509e-409d-b4da-fd5d2c0334ef)

**Comment by wre232114** [comment]
I see, I'll try pepka if I can

**Comment by wre232114** [comment]
I can not reproduce the runtime error of fela-vue. could you provide a repo that can reproduce this error

**Comment by houd1ni** [comment]
> I can not reproduce the runtime error of fela-vue. could you provide a repo that can reproduce this error

No, - it's a relatively large monorepo. I can cut it from there, but not very soon. Have you tried using `complement` function directly from pepka ?

**Comment by wre232114** [comment]
I think it's a issue related to lazy compilation based on the images above, i want to known is there a `import('fela-vue')` or `import('pepka')` in the project, so I can figure out what causes the error.

You can set `lazyCompilation` to `false` to see if the error solved.

**Comment by houd1ni** [comment]
> fixed in #1175 and will be released in `@farmfe/core@1.0.19`

Nope, that's not that issue. Still there. Also, there's only one place where I use dynamic import, is to import icons.
Maybe you can put in App.vue (root vue component) this part of code to reproduce:

```vue
<template>
  <div :class="f('flex actions')">
    qwe
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { css, Renderer } from 'fela-vue'
import { qmergeDeep } from "pepka"
import { styl } from '@/styles'

const common = css`
  .common-class {
    color magenta
  }
`

const felaOptions= {
  defStyles: () => qmergeDeep(common, css`
    .flex {display flex}
  `),
  preset: { unit: ['rem', {}] },
  modifiers: { m: false },
  ssr: true
}

const renderer = new Renderer(felaOptions)
const styl = renderer.styl

const f = computed(() => styl(css`
  .actions {
    gap 2
    margin-top 2
    > *:not(:first-of-type) { margin-left 2 }
    @media (max-width: 1050px) { margin-top 1.25 }
  }
`))
</script>
```

**Comment by wre232114** [comment]
I browsered code of fela-vue, it contains both import and dynamic import under dist/bundle.mjs. that's the cause of this issue. I also reproduced the error locally, I fixed this error and added a test case

**Comment by houd1ni** [comment]
Wow, I've completely forgotten that it's there under runtime compression part! Will review it - maybe, there's better ways to achieve the same now. But this helped as a test 😄

**Comment by houd1ni** [comment]
Yep! Looks like it works!
