### ISSUE TITLE
top level awaits seem to be not supported.

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1140]
### What problem does this feature solve?

`[Farm] Error loading dynamic module "virtual:FARMFE_DYNAMIC_IMPORT:C:\Users\pinke\p\as-examples\n-body\n-body\build\as_nbody.mjs" ReferenceError: await is not defined`

Hi again! Huge thank you for the work! I've attached a pretty simple assemblyscript output (.mjs + .wasm + .d.ts) that seems to be impossible to straightforward tune to wrap itself to anything but top-level awaits. Honestly, vite does not do anything with them too and has pretty the same error.

Is there a way to workaround this ?

[build.zip](https://github.com/farm-fe/farm/files/14900355/build.zip)

### What does the proposed API look like?

top-level awaits are supported by all modern browsers, and cracking this support by a bundler looks weird.

**Comment by wre232114** [comment]
Top level await is not supported for now. It will be supported soon.

**Comment by wre232114** [comment]
Top level await will be supported in `@farmfe/core@1.1.0`
