### ISSUE TITLE
Environment variable error

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1143]
### Steps to reproduce

build 命令，环境变量process.env.NODE_ENV 输出是 “development”

### What is expected?

.

### What is actually happening?

.

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 11.91 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

**Comment by ErKeLost** [comment]
![image](https://github.com/farm-fe/farm/assets/66500121/497cf1cb-8fb8-42fe-989e-95785214d352)

是不是手动又改掉了 NODE_ENV 呢

**Comment by ErKeLost** [comment]
@289420843  怎么复现呢 有 demo 么 具体步骤是什么

**Comment by 289420843** [comment]
@ErKeLost  试一下 [https://github.com/289420843/farm-test1](url)

**Comment by ErKeLost** [comment]
这个我看一下是为啥 你可以先使用 函数的方式
<img width="820" alt="image" src="https://github.com/farm-fe/farm/assets/66500121/f49126a8-3e9b-4099-bb83-cf2727806caa">
