### ISSUE TITLE
[Farm] Module "802c69e2" is not registered

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1150]
### Steps to reproduce

build 生产环境代码丢失，代码中存在`const _enums = farmRequire("802c69e2");` 但是不存在` "802c69e2":function .......`
![PixPin_2024-04-10_11-51-22](https://github.com/farm-fe/farm/assets/5706753/01638add-18ff-4c42-9d40-9ef859e56a06)

### What is expected?

。

### What is actually happening?

。

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 11.91 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
```

**Comment by wre232114** [comment]
把 compilation.mode 设置成 development 再 build 一下，看看报错的是哪个模块呢。然后看看能不能找到最小复现的 case

**Comment by wre232114** [comment]
这个有能复现的 case，或者比如说什么条件会影响到这个报错呢。比如关了 tree shake / minify 之后，这个错误是不是就消失了。我目前在我这里没法复现这个错误，需要更加精确的复现条件，才能更好的定位和解决问题

**Comment by 289420843** [comment]
是其他插件导致，暂时先关闭该问题，后续遇到再继续讨论
