### ISSUE TITLE
imported .png return plain objects instead of urls.

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1180]
### Steps to reproduce

- Create an empty vue 3 project.
- do `import img from '@/assets/img.png'` (I do it with alias, whatever).
- log it or use it.

### What is expected?

logs like this `/assets/qwe876qwe.png`

### What is actually happening?

logs this: `{}` without any props or specific prototype.

### System Info

```Shell
Win10x64 Pro latest, Intel 14600kf, 32Gb ram, almost empty.
```

### Any additional comments?

After [this](https://github.com/farm-fe/farm/issues/1128) and that templating issue, I've realized, that png still do not work.

**Comment by wre232114** [comment]
what's plugins you use? your plugin may transform images to objects. try `import img from '@/assets/img.png?url'` to see if it works

**Comment by houd1ni** [comment]
`?url` doesn't seem to do anything.

plugins:

```javascript
vitePlugins: [
    vueJsx(),
    namedDirectory(),
    vue(),
    // imagemin({}),
    svgLoader({defaultImport: 'component'}),
    rollupCSSCompression(),
    replace({
      preventAssignment: true,
      'process.env.PROJECT': JSON.stringify(__dirname.split(/[\\\/]/g).pop())
    }),
    process.env.NODE_ENV=='bundle-anal' && visualizer()
  ].filter(Boolean).map(({...p}, i) => ({...p, name: p.name || `vite_plugin_${i}`})),
  plugins: [
    {
      name: '[test-transform-html-pre]',
      transformHtml: {
        order: 0, // 0 means call this hook before parse and generate resources
        executor: async ({ htmlResource }) => {
          htmlResource.bytes = [...Buffer.from(Buffer
            .from(htmlResource.bytes as any)
            .toString()
            .replace('{head}', '<meta head />')
            .replace('{styles}', '<meta style />')
            .replace('{ssr}', '<meta ssr />')
          )]
          return htmlResource
        }
      }
    },
    {
      name: '[test-transform-html-post]',
      transformHtml: {
        order: 2, // 2 means call this hook after parse and generate resources
        executor: async ({ htmlResource }) => {
          htmlResource.bytes = [...Buffer.from(Buffer
            .from(htmlResource.bytes as any)
            .toString()
            .replace(/<meta (\w+?) \/>/g, '{$1}')
          )]
          return htmlResource
        }
      }
    }
  ]
```

Also I've tried 
```
assets: {
      include: ['png']
    },
```
in compilation.

**Comment by houd1ni** [comment]
Seems that commenting out `rollupCSSCompression` of fela-vue somehow does the trick. In vite or rollup it works perfectly though.

**Comment by houd1ni** [comment]
Also, take a look at `.map(({...p}, i) => ({...p, name: p.name || `vite_plugin_${i}`})),` line. This hack make it compatible with farm (porting from vite), by adding names to all plugins, even those that have not. Somehow farm throws on nonamed plugins.

**Comment by wre232114** [comment]
I see, it's compatibility issue of vite plugins, I'll try to fix it later

**Comment by houd1ni** [comment]
Yep, sure - it's done! Yoo-Hoo! 谢谢你，亲爱的朋友! 😃

**Comment by wre232114** [comment]
不客气！感谢支持和反馈
