### ISSUE TITLE
Runtime error after prod build

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1198]
### Steps to reproduce

- Successfully test a vue 3 project in dev(hmr) mode, fully on mocks without any external deps.
- Open in preview mode or build and open index.html.

### What is expected?

it's built and work.

### What is actually happening?

When in preview mode or just index file is open after build, this error is shown (btw all data is mocked):
![image](https://github.com/farm-fe/farm/assets/7501201/13595073-29f3-4288-9689-f35296df8d63)

vscode shows this:
![image](https://github.com/farm-fe/farm/assets/7501201/841acfea-8a59-42b6-978c-348083c8d360)

### System Info

```Shell
the same win10 latest node etc
```

### Any additional comments?

I'll provide any additional info if needed.

**Comment by houd1ni** [comment]
UPD that's how the bottom of generated index.html looks:
![image](https://github.com/farm-fe/farm/assets/7501201/7c4b211a-a0b8-4363-bac1-88ed7ffd30f5)

**Comment by houd1ni** [comment]
Fixed by myself: I've made some swc external during some research: `external: ["@swc/", '/swc.'],` that broke the build.

**Comment by wre232114** [comment]
Farm ensures strong consistency between development and production. You can enable production optimization like tree shake and minify in development to verify whether it works.
