### ISSUE TITLE
Runtime error after prod build

### ISSUE THREAD

**Issue by houd1ni** [farm-fe/farm#1199]
### Steps to reproduce

- Successfully test a vue 3 project in dev(hmr) mode, fully on mocks without any external deps.
- Build it.
- Open in preview mode or index.html directly.

### What is expected?

it's built and work.

### What is actually happening?

When in preview mode or just index file is open after build, this error is shown (btw all data is mocked):
(on localhost:1911) 
![image](https://github.com/farm-fe/farm/assets/7501201/cf71fadb-7dac-49b9-ac95-670cc4b2c168)

it is the last link in stacktrace, pretty long and without any entries by `localhost`:
![image](https://github.com/farm-fe/farm/assets/7501201/04acdf90-eef7-4f26-aa29-2781f0b91356)

### System Info

```Shell
Win10x64 Pro latest, latest node, Intel 14600kf, 32Gb ram, almost empty.
```

### Any additional comments?

I'll provide any additional info if needed.

**Comment by wre232114** [comment]
It seems that `URL` is from your business code, try set `minify: false` or `treeShake: false` to see whether it works.

**Comment by houd1ni** [comment]
![image](https://github.com/farm-fe/farm/assets/7501201/0dcae27d-fc99-46ce-af80-43fe28753f1c)

**Comment by wre232114** [comment]
`treeShaking`, see https://www.farmfe.org/docs/config/compilation-options#treeshaking.

You can disable `minify` and `treeShaking` one by one to figure out which one affects building

**Comment by wre232114** [comment]
thanks, we'll optimize error message and docs. Is it a compression issue? if it is, is there a example to reproduce the over compressed issue, so we can solve it

**Comment by houd1ni** [comment]
I mean, due to compression there are much of a hassle to found a bug 😄
