### ISSUE TITLE
Cannot find module '@farmfe/plugin-sass-linux-x64-gnu'

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1209]
### Steps to reproduce

执行 npm install ，检查node_modules/@farmfe/plugin-sass-linux-x64-gnu 是不存在的，不会自动安装依赖
"@farmfe/plugin-sass": "1.0.4"

### What is expected?

.

### What is actually happening?

.

### System Info

```Shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (8) x64 Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
    Memory: 6.26 GB / 7.79 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/nvm-0.39.7/versions/node/v16.18.1/bin/node
    npm: 8.19.2 - ~/.nvm/nvm-0.39.7/versions/node/v16.18.1/bin/npm
    pnpm: 8.15.7 - ~/.nvm/nvm-0.39.7/versions/node/v16.18.1/bin/pnpm
```

**Comment by wre232114** [comment]
用的源是淘宝的吗，之前遇到过淘宝的源缺失了依赖，可以试试npm官方的源

**Comment by 289420843** [comment]
> 用的源是淘宝的吗，之前遇到过淘宝的源缺失了依赖，可以试试npm官方的源

切换官方源也一样，在系统中直接运行npm install能安装完整，在jenkins里面安装不能，不知道哪里没对

**Comment by wre232114** [comment]
或者可以尝试用 `@farmfe/js-plugin-sass`

**Comment by 289420843** [comment]
好，我多试试先，不行就换@farmfe/js-plugin-sass
