### ISSUE TITLE
build 后若删除 .farm，导致之后的 npm dev 报错

### ISSUE THREAD

**Issue by LiMao00** [farm-fe/farm#1261]
### Steps to reproduce

示例仓库：https://gitee.com/limao-xs/farm-test-bug

重现步骤：
- pnpm i
- pnpm dev
- pnpm build
- 删除 .farm
- pnpm dev

报错如下图：
![image](https://github.com/farm-fe/farm/assets/99939885/7406af41-7650-4293-aa48-eaf40c7c3d85)

### What is expected?

正常执行

### What is actually happening?

定位到引起报错的位置是 shadcn/ui 的 `<HoverCard>` 组件，若是移除该组件，重现步骤不会报错
![image](https://github.com/farm-fe/farm/assets/99939885/508cf2dd-c986-4366-bb5a-351d90db182c)

预测：`<HoverCard>` 组件的 tailwind.css 导致报错。代码如下：
![image](https://github.com/farm-fe/farm/assets/99939885/98e2d19a-b560-43f3-9fdd-936b54b51038)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.24 GB / 7.89 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD        
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD      
  Browsers:
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^1.1.2 => 1.1.2
```

**Comment by wre232114** [comment]
![image](https://github.com/farm-fe/farm/assets/8372439/fcb97f07-83cf-4dd5-95b7-c88b02455c21)

unocss 里面限定 src 目录就可以了，这个是 unocss 的配置问题

**Comment by LiMao00** [comment]
> ![image](https://private-user-images.githubusercontent.com/8372439/329861301-fcb97f07-83cf-4dd5-95b7-c88b02455c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjE0OTEsIm5iZiI6MTcxNTU2MTE5MSwicGF0aCI6Ii84MzcyNDM5LzMyOTg2MTMwMS1mY2I5N2YwNy04M2NmLTRkZDUtOTViNy1jODhiMDI0NTVjMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMDA0NjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTUyNTIxNzY4NzViMmE1OWY5YmQ0ZTA1NjZlNjVlYzRmYmJiZDRmNmI2NGNmMWYzZjZhZTlkYzI1MDBjODhjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7y6OPkwx94GEKrVjWuXBbTDMjOKDh60eIDenNVK-oJE)
> 
> unocss 里面限定 src 目录就可以了，这个是 unocss 的配置问题

确实解决了问题 感谢
