### ISSUE TITLE
Using `build(opts)` API, `compilation.input` not work.

### ISSUE THREAD

**Issue by yejimeiming** [farm-fe/farm#1265]
### Steps to reproduce

```js
import { build } from '@farmfe/core';

build({
  compilation: {
    input: {
      main: 'electron/main.ts',
    },
  },
});
```

### What is expected?

Output an named `main.js` file to `dist` folder.

### What is actually happening?

Always output `index.html` to the `dist`.

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 83.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.20.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.14.3 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.92
    Safari: 15.3
  npmPackages:
    @farmfe/core: ^1.1.1 => 1.1.2
```

### Any additional comments?

I'll fix it in my next PR.

**Comment by fnicastri** [comment]
any progress on this?
I'm hitting this issue trying to migrate my project.
I have three ts entry points that I neeed to compile.

Using the compilation.input property make it unusable.

Any workaround?

I don't have an html entry point to use, building some widgets for a dotnet webapp.

**Comment by shulandmimi** [comment]
@fnicastri It's available now

your problem seems to be returning video/mp2t as a script. Can you provide a minimal reproducible issue?

**Comment by fnicastri** [comment]
I think I've added to the wrong issue.
I've erroneously deleted the project and can't reproduce, I made a lot of tweakings and don't remember when I hit the issue :(

I was trying to migrate a project from vite to farm,
but I encountered that issue and **the impossibility to set breakpoints** (always grey dots),
probably I have issues with the sourcemaps,
do you have an example of a working debuggable repo?

What about having many js/ts entry points?
The project is about some components (not web components) to integrate in a dotnet web app

**Comment by shulandmimi** [comment]
> but I encountered that issue and the impossibility to set breakpoints (always grey dots),

From the error, it seems that the content returned by the server is incorrect when loading video/mp2t resources through the network. You can check whether it is really a problem by opening chrome `networks`. then you can see where this resource is used in your source code

> What about having many js/ts entry points?

you can try [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)

**Comment by fnicastri** [comment]
> > but I encountered that issue and the impossibility to set breakpoints (always grey dots),
> 
> From the error, it seems that the content returned by the server is incorrect when loading video/mp2t resources through the network. You can check whether it is really a problem by opening chrome `networks`. then you can see where this resource is used in your source code

I was getting that mime on a ts file!


> > What about having many js/ts entry points?
> 
> you can try [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)

I would say that this is a less than ideal solution


Is this a supported scenario?
> I was trying to migrate a Svelte project from vite to farm,
> but I encountered that issue and the impossibility to set breakpoints (always grey dots),
> probably I have issues with the sourcemaps,
> do you have an example of a working debuggable repo? 

The project have two entrypoints, one svelte component and one ts file for the store (it is shared with the webapp)

any help?

**Comment by shulandmimi** [comment]
> I was getting that mime on a ts file!

It should be a server error. If you use `farm start`, then it is a problem with the farm server. If you encounter it again later, you can create an issues. If you use other methods to start the server, then you should check whether there is a problem with the server.

> I would say that this is a less than ideal solution

You are right, but it applies to most situations. I don't know enough about your environment to give you good advice (I am not familiar with dotnet web

> The project have two entrypoints, one svelte component and one ts file for the store (it is shared with the webapp)

[example](https://github.com/farm-fe/farm/tree/main/examples/arco-pro) You can try this project (I'm not sure if it will solve your problem), After starting, you can open it in Chrome, open the developer tools -> sources -> find the tab with the same domain name -> find your source code directory -> find the file you want to breakpoint -> start breakpoint
