### ISSUE TITLE
[Bug Report]: 通过脚本运行出现错误

### ISSUE THREAD

**Issue by LovePlayCode** [farm-fe/farm#1295]
### Steps to reproduce

import { BaseBundler, BaseBundlerBuildOpts, BaseBundlerOpts } from "./BaseBundler";
import { build, Server, logger, Compiler } from '@farmfe/core';
// import react from '@farmfe/plugin-react';

interface FarmOpts extends BaseBundlerOpts {
}

export class Farm extends BaseBundler {
  constructor(opts: FarmOpts) {
    super(opts);
  }

  async build(_opts: BaseBundlerBuildOpts = {}) {
    const buildOpts = {
      root: this.opts.root,
      plugins: [
        // react,
      ],
    };
    await build(buildOpts);
  }

  async dev(_opts: BaseBundlerBuildOpts = {}) {
    const buildOpts = {
      root: this.opts.root,
      output: {
        publicPath: '/',
      },
    };
    let compiler = new Compiler({
      config: buildOpts,
      jsPlugins: [
        // react,
      ],
      rustPlugins: [],
    });
    let server = new Server({
      compiler,
      logger,
    });
    await server.createServer({
      // @ts-ignore
      hmr: {
        port: 3000,
        host: '0.0.0.0',
      },
      port: 3000,
      host: '0.0.0.0',
    });
    server.listen();
  }
}

### What is actually happening?

正常编译
这个是错误图片
<img width="1030" alt="image" src="https://github.com/farm-fe/farm/assets/51304857/d943a533-c6e3-42dc-904f-0c895a99c095">

### System Info

```Shell
System: macos
Farm/core: 1.1.4
```

**Comment by wre232114** [comment]
我们看一下

**Comment by ErKeLost** [comment]
尝试用一下 `resolveConfig` 这个方法把options 传进去，然后在传入 `compiler` 中
