### ISSUE TITLE
[Bug Report]: 如果编译时存在public下面 index.html 会编译报错 

### ISSUE THREAD

**Issue by LovePlayCode** [farm-fe/farm#1307]
### Steps to reproduce

存在public下面的 index.html 编译报错

### What is actually happening?

存在public下面的 index.html 编译报错

### System Info

```Shell
··
```

**Comment by wre232114** [comment]
有复现步骤吗，没太看懂问题呢

**Comment by ErKeLost** [comment]
fixed in 1.3.0
