### ISSUE TITLE
[Bug Report]: Failed to run nestjs project

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#1340]
### Steps to reproduce

1. Do not know if many dependencies caused by optional dependencies are not installed and need to be installed manually
like this
<img width="1191" alt="image" src="https://github.com/farm-fe/farmup/assets/66500121/0d6638c0-73dc-4619-b0a4-372641e8d96a">

### Reproduce link

https://github.com/ErKeLost/test-nest

### What is actually happening?

start error need  Manual install all not resolve deps

### System Info

```Shell
mac
```

**Comment by denniarems** [comment]
![image](https://github.com/user-attachments/assets/098ef3db-d8eb-415c-a572-ff52fee28655)

**Comment by shulandmimi** [comment]
@denniarems 

Can you provide a minimal reproducible repository?

Or provide the following source code and the location of the error

1. Execute `farmup build --no-exec`
2. Use `node` to execute the entry file in the `dist` directory
3. Check the error stack and find the location of the error in the `dist` directory
4. Send screenshots of the source code and the error location
