### ISSUE TITLE
支持串行命名和驼峰命名相互转换

### ISSUE THREAD

**Issue by toplyb** [farm-fe/farm#1367]
### What problem does this feature solve?

css 类名通常使用串行（即中划线）命名，但是在 React 的 css module 中，使用驼峰命名又比较方便，所以期待可以在 css 配置中新增一项来让两者相互转换

### What does the proposed API look like?

如 webpack(https://www.webpackjs.com/loaders/css-loader#namedexport) 或者 vite 中的 `localsConvention` 一样

**Comment by wre232114** [comment]
我们看看
