### ISSUE TITLE
[Bug Report]: registerRuntimeCompiler is not a function

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1384]
### Steps to reproduce

1. git clone https://github.com/289420843/farm-test.git
2. cd farm-test
3. npm install
4. npm run build
5. npm run preview
6. 访问http://localhost:1911/ 
7. 控制台输出错误 registerRuntimeCompiler is not a function

### Reproduce link

https://github.com/289420843/farm-test.git

### What is actually happening?

cjs src/test.js 文件中导入vue模块会有 runtimeDom.registerRuntimeCompiler(compileToFunction); 代码，但是runtimeDom确没有registerRuntimeCompiler方法。

npm run dev 不会报错
降级到@farmfe/core: 1.1.12 错误消失

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.81 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @farmfe/core: 1.1.13 => 1.1.13
```

**Comment by wre232114** [comment]
farm core 1.1.14 修复了这个问题
