### ISSUE TITLE
[Bug Report]: 懒加载组件无法显示

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1418]
### Steps to reproduce

1. npm i
2. farm start
3. 访问 http://localhost:9000/ 无法显示home组件

### Reproduce link

https://github.com/289420843/farm-test.git

### What is actually happening?

受到配置影响
minify: {
      exclude: ["\\.html"],
    },

1. 控制台显示错乱
[ Farm ] ✓ Lazy compilation done(..\..\ est\
                                            arm-test\src\
                                                         iews\home.vue) in 3ms.
 2. 界面未显示 home组件

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.34 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @farmfe/core: 1.2.0 => 1.2.0
```

**Comment by hugang** [comment]
i have the same error when i import component dynamically.
```javascript
for (let p of pages) {
  let path = `../pages/${p.path}`;
  let Com = (await import(path)).default;
 ...
}

and i got error

![image](https://github.com/farm-fe/farm/assets/1448114/ed1056c1-1c4d-4a90-bc8a-3db24eb64d3b)

**Comment by wre232114** [comment]
> i have the same error when i import component dynamically.
> 
> ```js
> for (let p of pages) {
>   let path = `../pages/${p.path}`;
>   let Com = (await import(path)).default;
>  ...
> }
> 
> and i got error
> ![Snipaste_2024-06-26_10-45-51](https://github.com/farm-fe/farm/assets/1448114/251c52e1-5cc8-4a44-be93-c151dc7a8e8f)
> ```

This is not a same problem, you should use `import.meta.glob(xx)` if you want to batch import pages in farm. see https://www.farmfe.org/docs/features/script#vite-style-importmetaglob

**Comment by hugang** [comment]
```javascript
for (let p of pages) {
  let path = `../pages/${p.path}`;
  let Com = (await import.meta.glob(/* @vite-ignore */path)).default;
  childRoutes.push({
    path: p.pageId, element: <Com />
  })
}
```
Actually, what I need is to traverse the pages folder to set up routes. I don't think this solution fully addresses that.
