### ISSUE TITLE
[Bug Report]: Environment variables not loading from .env.production when using --mode production

### ISSUE THREAD

**Issue by valcosmos** [farm-fe/farm#1430]
### Steps to reproduce

1、pnpm create farm
2、choose `Vue2`

### What is actually happening?

I created a Vue 2 project using `pnpm create farm`. In the project root directory, I created three environment variable files: `.env`, `.env.development`, and `.env.production`. When I run the project using `pnpm dev --mode production`, it still reads the environment variables from the `.env.development` file. However, I want it to read the environment variables from the `.env.production` file. How should I proceed?

- .env
```
FARM_APP_SECRET=env
```
- .env.development
```
FARM_APP_SECRET=dev
```
- .env.production
```
FARM_APP_SECRET=prod
```

When I run the project using the command `pnpm dev --mode production`, and I try to access the environment variable in a component using `import.meta.env.FARM_APP_SECRET`, I always get the value defined in the .env.development file.

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 110.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.16 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.116
    Chrome Canary: 128.0.6555.0
    Safari: 17.5
  npmPackages:
    @farmfe/core: ^1.1.13 => 1.2.0
```

**Comment by valcosmos** [comment]
Any feedback would be greatly appreciated 🥺

**Comment by LogicHou** [comment]
差不多的问题，运行npm run build命令的时候不会使用.env.production中的变量值

**Comment by ErKeLost** [comment]
> 差不多的问题，运行npm run build命令的时候不会使用.env.production中的变量值

问题解决完了 一会发版

**Comment by valcosmos** [comment]
> > 差不多的问题，运行npm run build命令的时候不会使用.env.production中的变量值
> 
> 问题解决完了 一会发版

非常感谢 🙏

**Comment by ErKeLost** [comment]
> > > 差不多的问题，运行npm run build命令的时候不会使用.env.production中的变量值
> > 
> > 
> > 问题解决完了 一会发版
> 
> 非常感谢 🙏

还在跑 ci 下午应该可以发

**Comment by ErKeLost** [comment]
fixed in 1.2.5 试一下这个版本

**Comment by LogicHou** [comment]
> fixed in 1.2.5 试一下这个版本

可以了，强哦
