### ISSUE TITLE
[Feature Request]: Can not resolve `@/xxxxxx` from jsx file

### ISSUE THREAD

**Issue by hugang** [farm-fe/farm#1442]
### What problem does this feature solve?

i am use @ for src folder in vite, here is my config. 
and now i am tring to use farm but i got an error.
Can not resolve `@/xxxxxx` from jsx file.
can i do the same thing in farm?

alias: {
      "@": path.resolve(__dirname, "src"),
    },

### What does the proposed API look like?

use @ as src

**Comment by wre232114** [comment]
What's your farm.config.ts? You should use:

```diff
import { defineConfig } from '@farmfe/core';
import Vue from '@vitejs/plugin-vue'
import farmJsPluginLess from '@farmfe/js-plugin-less';
import path from 'path';


export default defineConfig({
  compilation: {
    resolve: {
+      alias: {
+       '/@': path.join(process.cwd(), 'src')
+     }
    }
  },
  plugins: [farmJsPluginLess()],
  vitePlugins: [Vue()]
});
```
see https://github.com/farm-fe/farm/blob/main/examples/vue-antdv/farm.config.ts

**Comment by hugang** [comment]
thx. close it.
