### ISSUE TITLE
[Feature Request]: Allow bundling entire dist into a single file

### ISSUE THREAD

**Issue by spikecodes** [farm-fe/farm#1498]
### What problem does this feature solve?

Our project infrastructure utilizes [`vite-plugin-singlefile`](https://www.npmjs.com/package/vite-plugin-singlefile) to _inline_ all JavaScript and CSS resources directly into the final dist/index.html file.

This allows us to create easily portable single files for each submodule of our project.

### What does the proposed API look like?

Either a dedicated config flag (e.g. `compilation.singleFile: true`) or a Farm-compatible alternative to `vite-plugin-singlefile` which throws an error with `farm build`:

```
Inlining: index_3aed.bd2c50fe.js
[ Farm ] Failed to build: Error: html.replace is not a function
TypeError: html.replace is not a function
    at replaceScript (file:///C:/Users/micro/Documents/coding/browser/node_modules/vite-plugin-singlefile/dist/esm/index.js:7:26)
    at Object.generateBundle (file:///C:/Users/micro/Documents/coding/browser/node_modules/vite-plugin-singlefile/dist/esm/index.js:62:40)
    at file:///C:/Users/micro/Documents/coding/browser/node_modules/@farmfe/core/dist/plugin/js/vite-plugin-adapter.js:438:29
    at file:///C:/Users/micro/Documents/coding/browser/node_modules/@farmfe/core/dist/plugin/js/vite-plugin-adapter.js:151:30
```

**Comment by spikecodes** [comment]
I created a plugin for this here: https://www.npmjs.com/package/@portalcorp/farm-plugin-singlefile

Basically ported vite-plugin-singlefile to farm

**Comment by ErKeLost** [comment]
Looks like we can close this issue. Thanks for your contribution.
