### ISSUE TITLE
[Bug Report]: SVG displays correctly in dev mode but fails to show after build

### ISSUE THREAD

**Issue by valcosmos** [farm-fe/farm#1499]
### Steps to reproduce

1、git clone https://github.com/valcosmos/farm-starter.git
2、pnpm i
3、pnpm dev    (In this case, the SVG displays correctly.)
4、pnpm build
5、pnpm preview  (But in this case, it fails to display, and the page is blank.)

### Reproduce link

https://github.com/valcosmos/farm-starter.git

### What is actually happening?

I'm using the `vite-plugin-svg-icons` plugin to process local SVG icons. However, I've noticed that while the icons display correctly during development (dev mode), they fail to show up after building the project (production build).

when dev:
![image](https://github.com/farm-fe/farm/assets/53572196/7b3f3a9b-78b4-49e1-af79-ccd137c0bd31)

when after build:
![image](https://github.com/farm-fe/farm/assets/53572196/22dee9c2-1175-47d1-bb8e-bf7572b81d1c)

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 71.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.17 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 128.0.6570.0
    Safari: 17.5
```

**Comment by valcosmos** [comment]
Any response would be greatly appreciated.🥺

**Comment by wre232114** [comment]
I'll take a look

**Comment by valcosmos** [comment]
> I'll take a look

Thank u so much 🙏😊
