### ISSUE TITLE
[Bug Report]: farm build hang in Bun docker

### ISSUE THREAD

**Issue by erguotou520** [farm-fe/farm#1505]
### Steps to reproduce

First, create a bun docker container:
```shell
docker run -it oven/bun:1-slim /bin/sh
```
Then, run the following scripts in the container:
```shll
bun create farm@latest test
cd test
bun i
bun run build
```

### What is actually happening?

The task will not exit even the build command finished.

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 170.58 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.5.1 - ~/Library/pnpm/pnpm
    bun: 1.1.17 - ~/.bun/bin/bun
```

**Comment by erguotou520** [comment]
> Work around:
> 
> `_build.ts`
> 
> ```ts
> import { spawn } from "bun";
> 
> const build = spawn({ cmd: ["bunx", "farm", "build"] });
> 
> for await (const line of build.stdout) {
> 	const strLine = Buffer.from(line).toString();
> 	console.write(strLine);
> 	if (strLine.includes("Public directory resources copied")) process.exit(0);
> }
> ```
> 
> in your `package.json`
> 
> ```json
> {
> 	[...]
> 	"scripts": {
> 		[...]
> 		"build": "bun run _build.ts",
> 		[...]
> 	},
> 	[...]
> ```
> 
> in your `Dockerfile`:
> 
> ```dockerfile
> [...]
> RUN bun run build
> [...]
> ```

Yes, just a work around, not the best resolution.

**Comment by chneau** [comment]
@erguotou520 Hello, it seems to be fixed with the new version of farm, 
```json
		"@farmfe/cli": "^1.0.3",
		"@farmfe/core": "^1.3.12",
		"@farmfe/plugin-react": "^1.2.0",
		"@farmfe/plugin-sass": "^1.1.0",
```

working perfect in docker for me now

**Comment by erguotou520** [comment]
Well done.
