### ISSUE TITLE
Electron + react template: Failed to construct 'WebSocket': The URL 'ws://localhost:9000__hmr' is invalid. [Bug Report]: 

### ISSUE THREAD

**Issue by GustavoGomez092** [farm-fe/farm#1522]
### Steps to reproduce

`npm create farm@latest my-react-app`
Then select electron and React template

### What is actually happening?

HMR not working after clean `npm install` and `npm run dev`
with error: 

<p style="color:red;">Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:9000__hmr' is invalid.</p>

<img width="1178" alt="image" src="https://github.com/farm-fe/farm/assets/45272016/d8348fd6-8967-4d81-b50a-6ac3ff76bb5f">

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 552.19 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
    Safari Technology Preview: 17.4
  npmPackages:
    @farmfe/core: ^1.2.4 => 1.2.6
```

**Comment by ErKeLost** [comment]
i'll try it
