### ISSUE TITLE
[Bug Report]: Tailwind does not work

### ISSUE THREAD

**Issue by kaiser101** [farm-fe/farm#1544]
### Steps to reproduce

Followed the steps given on this page

https://tailwindcss.com/docs/guides/vite

### What is actually happening?

Tailwind classes are not being picked up. I do not see any styling

### System Info

```Shell
System: Windows 10
Binaries: bun, farm
```

**Comment by wre232114** [comment]
You need to install @farmfe/js-plugin-postcss and configuring tailwindcss in postcss config

**Comment by ErKeLost** [comment]
examle https://github.com/farm-fe/farm/tree/main/examples/tailwind

**Comment by kaiser101** [comment]
Thanks this can be closed.
