### ISSUE TITLE
[Bug Report]: Farm unable to use `unplugin-imagemin`

### ISSUE THREAD

**Issue by fu050409** [farm-fe/farm#1549]
### Steps to reproduce

1. Setup a farm project and configure `unplugin-imagemin`.

2. Run `pnpm build`

### Reproduce link

https://github.com/fu050409/farm-imagemin-example

### What is actually happening?

Failed to build by `farm`:

![image](https://github.com/farm-fe/farm/assets/46275354/6afd0697-283b-4b01-86a5-66de90909af6)

But build properly by `vite`:

![image](https://github.com/farm-fe/farm/assets/46275354/097586c0-17f0-4e94-a368-07e5dee00d3e)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 3.48 GB / 15.64 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.0.31 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: ^1.2.8 => 1.2.8
```

**Comment by ErKeLost** [comment]
`unplugin-imagemin` not support farm by now,I probably won’t consider supporting farm in the future, because it’s quite hacky. we can think about implacement write with rust plugin  😆😆😆 , If you would like to contribute you are more than welcome
