### ISSUE TITLE
[Bug Report]: 动态导入css文件控制台报错

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1551]
### Steps to reproduce

import("./test.css");
存在动态导入css的代码运行时报错：Dynamic imported module "xxxxx" is not registered.
但实际在运行时可以正确的加载样式文件并让样式生效，所以我认为不应该出现这个错误信息。

### What is actually happening?

.

### System Info

```Shell
.
```

**Comment by wre232114** [comment]
我们看看，应该是生产构建这个 动态css导入语句没有被移除

**Comment by sLin90** [comment]
@wre232114 
我发现这种写法还是会报错
test("tes", () => import("xxxx.css"));

**Comment by sLin90** [comment]
@wre232114

**Comment by wre232114** [comment]
我再看看，这个应该修复了
