### ISSUE TITLE
[Bug Report]: Farm module load bug

### ISSUE THREAD

**Issue by eryue0220** [farm-fe/farm#1555]
### Steps to reproduce

I‘m writing a farm plugin through `unplugin`; and I found farm maybe has a bug when loading module. The bug code likes:

```js
import * as stylex from '@stylexjs/stylex'
import { colors } from '@stylexjs/open-props/lib/colors.stylex'
import { sizes } from '@stylexjs/open-props/lib/sizes.stylex'
import { fonts } from '@stylexjs/open-props/lib/fonts.stylex'

const styles = stylex.create({
  main: {
    // ...
    backgroundColor: colors.pink7,
  },
  card: {
   // ...
    backgroundColor: colors.blue9,
    padding: sizes.spacing5,
    borderRadius: sizes.spacing2,
    fontFamily: fonts.mono,
  },
})

function App() {
  // add this code, everything will work
  console.log('app::', colors.pink7, sizes, fonts.mono)

  return (
    <div {...stylex.props(styles.main)}>
  
    </div>
  )
}
```

and Farm won't load the module `@stylesjs/open-props`, if I remove the `console.log`: 
```js
import { colors } from '@stylexjs/open-props/lib/colors.stylex'
import { sizes } from '@stylexjs/open-props/lib/sizes.stylex'
import { fonts } from '@stylexjs/open-props/lib/fonts.stylex'
```

### Reproduce link

https://github.com/eryue0220/unplugin-stylex/tree/feat/support-farm/examples/farm-example

### What is actually happening?

The module `@stylexjs/open-props` didn't load at all.

### System Info

```Shell
System: mac os
Binaries: nodejs v20.14.0, farm
```

**Comment by shulandmimi** [comment]
After some plugins, `colors.gray0` will be converted to `"var(--x10amyqq)"`, and colors will become unused dead code, which will be deleted by tree shaking. But the css variable seems to be dynamically defined in `@stylexjs/open-props/lib/colors.stylex`, so the css variable cannot be found.

A temporary solution is to set `complation.treeShaking` to false in `farm.config.ts`

**Comment by shulandmimi** [comment]
I looked at the configuration of other Builders and I think you should set [treeshakeCompensation](https://stylexjs.com/docs/api/configuration/babel-plugin/#treeshakecompensation) to true like other builders

**Comment by eryue0220** [comment]
Yes. I see. the [treeshakeCompensation](https://stylexjs.com/docs/api/configuration/babel-plugin/#treeshakecompensation) in other builders is an optinal property, but farm is not.

**Comment by shulandmimi** [comment]
treeShaking is enabled by default in production environments, but in development environments is a bug, we will fix it later, sorry for the inconvenience.
