### ISSUE TITLE
[Bug Report]:  Deploy UnexpectedEof

### ISSUE THREAD

**Issue by biscet** [farm-fe/farm#1559]
### Steps to reproduce

[ Farm ] Using config file at /builds/frontend/config/farm.prod.js
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sass-embedded-0.7.1/src/varint.rs:8:30:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace

### What is actually happening?

Everything is fine on a personal computer, but when deployed it breaks, what should I do?

### System Info

```Shell
OS: Alpine x64
```

**Comment by wre232114** [comment]
Try use `@farmfe/js-plugin-sass` instead.
