### ISSUE TITLE
[Bug Report]: Port arg not working

### ISSUE THREAD

**Issue by Micnubinub** [farm-fe/farm#1595]
### Steps to reproduce

Copied this config from  [https://www.farmfe.org/docs/features/dev-server#configuring-dev-server](https://www.farmfe.org/docs/features/dev-server#configuring-dev-server) and it seems as though the `port` argument doesn't work
<img width="761" alt="SCR-20240712-buwj" src="https://github.com/farm-fe/farm/assets/4921356/67afe158-182b-4f1d-b1de-4cf95096a35a">
<img width="895" alt="SCR-20240712-bvdo" src="https://github.com/farm-fe/farm/assets/4921356/53c122e1-0687-4308-be35-4a1b5dc8043b">

### What is actually happening?

Preview selects a random port number

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 55.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.1 - /opt/homebrew/bin/node
    npm: 10.8.0 - /opt/homebrew/bin/npm
    bun: 1.1.18 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @farmfe/core: 1.2.8 => 1.2.8
```

**Comment by fu050409** [comment]
We'll take a look
