### ISSUE TITLE
[Bug Report]: The Tauri/React bundle isn't working.

### ISSUE THREAD

**Issue by Estereg** [farm-fe/farm#1604]
### Steps to reproduce

1. npm create farm@latest
2. select tauri
3. select react
4. Put name
5. cd name
6. npm i
7. npm run build
8. Open the build directory and open index.html in your browser
9. Check the console for any errors

### What is actually happening?

In the bundle, files are incorrectly imported, including images and other assets. This issue needs to be investigated further. The page literally shows nothing.

### System Info

```Shell
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Memory: 9.88 GB / 15.90 GB
Binaries:
  Node: 22.4.1 - C:\Program Files\nodejs\node.EXE
  npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Internet Explorer: 11.0.22621.1
npmPackages:
  @farmfe/core: ^1.2.4 => 1.2.8
```

**Comment by fu050409** [comment]
We'll take a look

**Comment by fu050409** [comment]
Modern browsers will deny all insecure access, and opening the entry file directly will be blocked by the browser. You can either try to see if the compiled exe file works after executing `pnpm tauri build`, or run `pnpm preview` and open it in a browser.

**Comment by Estereg** [comment]
![image](https://github.com/user-attachments/assets/c54174f1-8b03-4403-a94e-d49e69d4bea9)
Yeah, but does it really create an .exe? I've only seen the bundle of HTML, CSS, and JavaScript. Besides, when you try to bundle it, TypeScript gives an error for some reason. That's why I created a file called declare.ts with this code, and only then can I run it
```
declare module '*.svg' {
    const content: any;
    export default content;
}

declare module '*.png' {
    const content: any;
    export default content;
}
```

**Comment by Estereg** [comment]
And dist no have a .exe or am I wrong? 
![image](https://github.com/user-attachments/assets/f4898b95-ccc7-4cf0-9b3f-e8c7fd7df28d)

**Comment by fu050409** [comment]
> And dist no have a .exe or am I wrong? 
> ![image](https://github.com/user-attachments/assets/f4898b95-ccc7-4cf0-9b3f-e8c7fd7df28d)
> 

Tauri should run `pnpm tauri build` instead of `pnpm build`. The previous is building tauri and the latter is building frontend. For more info please see [Tauri Documentation](https://tauri.app/)

**Comment by Estereg** [comment]
Thanks bro

**Comment by fu050409** [comment]
> Thanks bro, before with vite it was just npm run build, sorry

Never mind :)

**Comment by fu050409** [comment]
I will close this issue soon. If you have any new questions, feel free to reply here :)

**Comment by Estereg** [comment]
hanks bro, I reinstalled everything: React, Tailwind, Farm, Tauri, and now it works on Brave.
![image](https://github.com/user-attachments/assets/b80e3f38-2b41-4f74-9e30-48cdda1169e0)
![image](https://github.com/user-attachments/assets/65c3e879-af28-4146-9382-de415d69716a)

**Comment by Estereg** [comment]
But I found another problem, I think. Now, using Tailwind, the page doesn't work. If you could test it, it would clear my doubt.
