### ISSUE TITLE
[Bug Report]: Tauri/React template missing module declaration

### ISSUE THREAD

**Issue by fu050409** [farm-fe/farm#1605]
### Steps to reproduce

> Besides, when you try to bundle it, TypeScript gives an error for some reason. That's why I created a file called declare.ts with this code, and only then can I run it
> ```
> declare module '*.svg' {
>     const content: any;
>     export default content;
> }
> 
> declare module '*.png' {
>     const content: any;
>     export default content;
> }
> ```
> 
> _Originally posted by @Estereg in https://github.com/farm-fe/farm/issues/1604#issuecomment-2227042712_
> 

### What is actually happening?

see above

### System Info

```Shell
any
```

**Comment by Estereg** [comment]
I have already created a pull request for this, and it has been merged into the main branch. Please review the changes.
https://github.com/farm-fe/farm/pull/1571#event-13451051845

**Comment by fu050409** [comment]
> I have already created a pull request for this, and it has been merged into the main branch. Please review the changes. [#1571 (comment)](https://github.com/farm-fe/farm/pull/1571#event-13451051845)

Okay, thanks for the heads up
