### ISSUE TITLE
[Bug Report]: Farm 1.2.8 working while 1.3.0+ fails

### ISSUE THREAD

**Issue by melloware** [farm-fe/farm#1670]
### Steps to reproduce

Reproducer:
[webui.zip](https://github.com/user-attachments/files/16394545/webui.zip)

1. Unzip attached file
2. Run `npm i`
3. Run `npm run dev`

You will see it work. Now

1. Update `package.json` to latest Farm 1.3.11
2. Run `npm i`
3. Run `npm run dev`

Fails

### Reproduce link

See zip file above...

### What is actually happening?

Now on compilation it fail with the following log:

```
[ Farm ] Using config file at C:\dev\quarkus\quarkus-monorepo\src\main\webui\farm.config.ts
[ building ] ⠂ transform (223) node_modules/primereact/icons/trash/index.esm.js                                         [ Farm ] Error: Failed to start the server
Caused by: Error: Can not resolve `primereact/menuitem` from src/AppMenuItem.ts.
Original error: None.

Potential Causes:
1.The file that `primereact/menuitem` points to does not exist.
2.Install it first if `primereact/menuitem` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `primereact/menuitem` is a alias, make sure your alias config is correct.

    at logError (file:///C:/dev/quarkus/quarkus-monorepo/src/main/webui/node_modules/@farmfe/core/dist/server/error.js:74:15)
    at Server.compile (file:///C:/dev/quarkus/quarkus-monorepo/src/main/webui/node_modules/@farmfe/core/dist/server/index.js:62:29)
    at async Server.listen (file:///C:/dev/quarkus/quarkus-monorepo/src/main/webui/node_modules/@farmfe/core/dist/server/index.js:44:9)
    at async start (file:///C:/dev/quarkus/quarkus-monorepo/src/main/webui/node_modules/@farmfe/core/dist/index.js:31:9)
    at async handleAsyncOperationErrors (file:///C:/dev/quarkus/quarkus-monorepo/src/main/webui/node_modules/@farmfe/cli/dist/utils.js:111:9)
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12800HX
    Memory: 13.34 GB / 31.70 GB
  Binaries:
    Node: 20.14.0 - C:\tools\node-v20.14.0-win-x64\node.EXE
    Yarn: 3.5.0 - C:\tools\node-v20.14.0-win-x64\yarn.CMD
    npm: 10.7.0 - C:\tools\node-v20.14.0-win-x64\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: 1.2.8 => 1.2.8
```

**Comment by wre232114** [comment]
change `import { MenuItem } from 'primereact/menuitem';` to `import type { MenuItem } from 'primereact/menuitem';` works in 1.3.0+

**Comment by wre232114** [comment]
Related issue #1555. Before 1.3.0, all unused imports will be removed, then `import { MenuItem } from 'primereact/menuitem';` is removed  and it works. But this would cause issue #1555 - all unused imports(even them are value import), and this behavior is limited by swc, we can not just erase the type import when using swc to strip type for now. So you have to use `import type { MenuItem } from 'primereact/menuitem';` to declare it as `type import`.

**Comment by melloware** [comment]
Thank you for pointing this out.  I guess I never realized it should have been `import type`. That does indeed fix it!
