### ISSUE TITLE
[Bug Report]: `farm build` not working when using naive-ui

### ISSUE THREAD

**Issue by 0x1997** [farm-fe/farm#1672]
### Steps to reproduce

1. cd farm-naiveui
2. bun install
3. bun run build
4. cd dist
5. python -m http.server
6. open url in browser, find `ReferenceError: createKey is not defined` in console

### Reproduce link

https://github.com/0x1997/farm-naiveui

### What is actually happening?

The page works fine when running `bun run dev`.
Setting `complation.treeShaking` to false in farm.config.ts doesn't work.

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.76 GB / 15.79 GB
  Binaries:
    Node: 21.7.3 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: ^1.3.11 => 1.3.11
```

**Comment by shulandmimi** [comment]
The problem is caused by `compilation.minify.moduleDecls`, which is enabled by default in production. You can manually set it to false to disable it. We will fix it later.
