### ISSUE TITLE
Does not support Termux (Android arm64)

### ISSUE THREAD

**Issue by n-ce** [farm-fe/farm#1687]
### Steps to reproduce

1. Install nodejs in termux
2. npm create farm@latest

### What is actually happening?

![Screenshot_20240801-143231_1](https://github.com/user-attachments/assets/8c96c216-6ee0-4c33-9392-6ded31500690)

### System Info

```Shell
System:
    OS: android
    CPU: Unknown
    Memory: 1.68 GB / 3.66 GB
  Binaries:
    Node: 22.4.1 - /data/data/com.termux/files/usr/bin/node
    Yarn: 1.22.22 - /data/data/com.termux/files/usr/bin/yarn
    npm: 10.8.1 - /data/data/com.termux/files/usr/bin/npm
    pnpm: 9.6.0 - /data/data/com.termux/files/usr/bin/pnpm
```
```

**Comment by fu050409** [comment]
You can try to install a ubuntu environment(or any other supported sys) on Termux by [`proot-distro`](https://github.com/termux/proot-distro) as a temporarily solution. We will fix this as soon as possible.

**Comment by n-ce** [comment]
@fu050409 Thank you for fixing this.

I haven't attended to farm ever since. But upon trying it currently, I'm having this issue on `npm run dev` 
I'm trying the Tauri2+Solid Template, rest of the system info remain similar.
Can you please take a look?

![Image](https://github.com/user-attachments/assets/eade1553-2f4b-49aa-8387-4778740dd25e)

**Comment by fu050409** [comment]
@n-ce hi, have you tried to set up a real linux chroot environment and retry? the env will be detected as android in termux directly but aarch64 linux in virtual ubuntu

**Comment by n-ce** [comment]
> [@n-ce](https://github.com/n-ce) hi, have you tried to set up a real linux chroot environment and retry? the env will be detected as android in termux directly but aarch64 linux in virtual ubuntu

I have known of Proot which you mentioned earlier, but I have not had the need for it in years of termux usage, everything I need works natively except for Bun. Vite has no compatibility issues that is why feel farm shouldn't have either, though I understand farm may require the presence of more native binaries.
