### ISSUE TITLE
[Bug Report]: Cannot find package 'src'

### ISSUE THREAD

**Issue by blaicer15** [farm-fe/farm#1690]
### Steps to reproduce

When running the **yarn run de**v command, it mentions that it cannot find the **"src"** folder, it works if I compile the project as if it were a NestJs

### What is actually happening?

When compiling with the NestJs Framework, it gives an error when searching for the "src" folder, even when using it to make an alias: [Configuring Alias And Externals](https://www.farmfe.org/docs/tutorials/start/#configuring-alias-and-externals)

[ Farmup ] "index" PID 10771 exit 1
[ Farmup ] Build completed in 390ms ⚡️FULL EXTREME! Resources emitted to ./dist.
[ Farmup:index ] node:internal/modules/esm/resolve:845
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'src' imported from ~/proyectos/backend/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:845:9)
    at moduleResolve (node:internal/modules/esm/resolve:918:18)
    at defaultResolve (node:internal/modules/esm/resolve:1148:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.7.3

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.57 GB / 7.71 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    Yarn: 4.3.1 - ~/.nvm/versions/node/v21.7.3/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
    pnpm: 9.5.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 127.0.6533.88
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.10
```

**Comment by ErKeLost** [comment]
Can you provide a reproduce link？ We can solve problems faster

**Comment by blaicer15** [comment]
But I'm just running the **"yarn run dev"** command, I don't have a link where you can reproduce the problem, since it's a private project for a company. How can I generate a link for you in a project that I generated publicly?

**Comment by blaicer15** [comment]
In order for the project to work, I just had to make an empty project and put all the information inside. "I literally copied the information from my **'old'** project, created with the same version of **farmfe** and pasted it into **my new project**, so it would work." I hate my PC @ErKeLost

**Comment by blaicer15** [comment]
In order for the project to work, I just had to make an empty project and put all the information inside. "I literally copied the information from my **'old'** project, created with the same version of **farmfe** and pasted it into **my new project**, so it would work." I hate my PC @ErKeLost

**Comment by ErKeLost** [comment]
Thank you for your feedback and use farm @blaicer15
