### ISSUE TITLE
[Bug Report]: ReferenceError: __dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by blaicer15** [farm-fe/farm#1695]
### Steps to reproduce

1.- Instalar la libreria bcrypt desde la pagina oficial.
2.- importarlo: import * as bcrypt from "bcrypt"; (importacion extraida de la propia documentacion de bcrypt)
3.- utilizar como lo mencionan en la libreria
const salt = await bcrypt.genSalt()
    const pass = await bcrypt.hash(password, salt)

### Reproduce link

https://gitlab.com/blaicer/farmfe-bcrypt.git

### What is actually happening?

There is a problem compiling the bcrypt library, it gives the following error: ReferenceError: __dirname is not defined in ES module scope

error reference:
[ Farmup:index ] file:///home/projects/farmfe/backend/dist/index.mjs_43e7.21afa2a8.mjs:5
var binding_path = nodePreGyp.find(path.resolve(path.join(__dirname, './package.json')));

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.57 GB / 7.71 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    Yarn: 4.3.1 - ~/.nvm/versions/node/v21.7.3/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
    pnpm: 9.5.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 127.0.6533.88
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.12
```

**Comment by shulandmimi** [comment]
This is because the bcrypt package uses __dirname, but in `index.plugin.ts` `compilation.output.format`, the code is compiled to esm by default

Therefore, you need to output cjs in `farm.config.ts`, and the configuration is as follows

> In addition, I found [this problem](https://github.com/kelektiv/node.bcrypt.js/issues/573) during the modification process. The reason for this is that it is required by this library. Its [solution is as follows](https://github.com/kelektiv/node.bcrypt.js/issues/573#issuecomment-378567607) (already included in the following configuration), Of course, you can also look for some other solutions

```ts
import { defineConfig } from '@farmfe/core';
import NestPlugin from './index.plugin';

export default defineConfig({
  plugins: [NestPlugin()],
  compilation: {
    output: {
      format: 'cjs',
      filename: '[name].[ext]',
    },
	// fix https://github.com/kelektiv/node.bcrypt.js/issues/573
    external: ['bcrypt']
  },
});

```

**Comment by blaicer15** [comment]
Thank you very much @shulandmimi, I don't think I would have ever found this on my own. I will use your solution, it was effective.
