### ISSUE TITLE
[Bug Report]: Bcrypt (package_json_path does not exist)

### ISSUE THREAD

**Issue by Altro31** [farm-fe/farm#1706]
### Steps to reproduce

bun dev

### Reproduce link

https://github.com/Altro31/bcrypt-farm-test.git

### What is actually happening?

![image](https://github.com/user-attachments/assets/1bd83a24-df11-4826-a75e-53c60fa5fbad)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 AMD Athlon 200GE with Radeon Vega Graphics
    Memory: 11.33 GB / 21.92 GB
  Binaries:
    Node: 22.0.0 - D:\Dev\nodejs\node.EXE
    npm: 10.6.0 - D:\Dev\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.12
```

**Comment by ErKeLost** [comment]
You can temporarily modify the config file like this，We have a rust plugin but it doesn't seem to be working, I'll look into this issue

```ts
import { defineConfig } from '@farmfe/core';
import NestPlugin from './index.plugin';
import path from 'path';
import { pathToFileURL } from 'url';

console.log(__dirname);
export default defineConfig({
  plugins: [replaceDirnamePlugin(), NestPlugin()],
  compilation: {
    output: {
      filename: '[name].[ext]',
      format: 'cjs',
    },
  },
});

export function replaceDirnamePlugin() {
  const moduleTypes = ['ts', 'js', 'cjs', 'mjs', 'mts', 'cts'];
  const resolvedPaths: string[] = [];
  return {
    name: 'replace-dirname',
    transform: {
      filters: {
        moduleTypes,
        resolvedPaths,
      },
      async executor(param) {
        const { content, resolvedPath, moduleType } = param;
        let replaceContent = content;
        const dirPath = path.dirname(resolvedPath);

        replaceContent = param.content.replace(
          /__dirname/g,
          JSON.stringify(dirPath),
        );

        return {
          content: replaceContent,
          moduleType,
        };
      },
    },
  };
}

```

**Comment by shulandmimi** [comment]
https://github.com/farm-fe/farm/issues/1695#issuecomment-2270489369

> In addition, I found [this problem](https://github.com/kelektiv/node.bcrypt.js/issues/573) during the modification process. The reason for this is that it is required by this library. Its [solution is as follows](https://github.com/kelektiv/node.bcrypt.js/issues/573#issuecomment-378567607) (already included in the following configuration), Of course, you can also look for some other solutions

This is a limitation caused by the library's functionality. The above content contains the cause of the problem and the solution to the problem.

**Comment by shulandmimi** [comment]
Another option is to find alternatives, which should be useful for applications in the early stages of the project.

https://github.com/kelektiv/node.bcrypt.js/issues/573#issuecomment-450939186
