### ISSUE TITLE
现在能在开发环境使用吗。

### ISSUE THREAD

**Issue by tzwhyqq** [farm-fe/farm#173]
### What problem does this feature solve?

一直用的vite，vite初次启动太慢，一个稍微大一点（50-80个页面）的项目启动一次就要1分钟，一直被我诟病，看到咱们项目的对比速度。想在开发环境试试。我用vue3+elmentplus 发现运行不了，还是我配置问题。

### What does the proposed API look like?

vue3 和 element plus 或者 antv 3/4。能够开发环境使用。

**Comment by wre232114** [comment]
需要看你们的项目用了哪些技术栈呢，vue 的有些功能我们还没支持，比如 jsx

**Comment by tzwhyqq** [comment]
less ，saas 。 我现在就简单的element plus/antd vue 。没其他任何组件。

**Comment by wre232114** [comment]
react 的支持好一些，引用组件库的话，可能引入了 sass less，这些需要安装额外的插件

**Comment by tzwhyqq** [comment]
是的。我看了下，好像就是sass less 这些不行

**Comment by tzwhyqq** [comment]
这些 额外的插件 还是有现成的吗，还是在开发

**Comment by tzwhyqq** [comment]
sass less，这些需要安装额外的插件 这个插件，是还在开发中还是。有现成的，我看vite是有相关的插件。

**Comment by wre232114** [comment]
有官方插件，我更新下文档以及带组件库的示例

**Comment by tzwhyqq** [comment]
已解决
