### ISSUE TITLE
[Bug Report]: 多页面打包配置isolate=true时，页面无法正常显示

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#1754]
### Steps to reproduce

1. git clone https://github.com/289420843/farm-test.git
2. cd farm-test
3. npm install
4. npm run build
5. npm run preview
6. 访问 http://localhost:1911 
7. 访问 http://localhost:1911/test.html

### Reproduce link

https://github.com/289420843/farm-test.git

### What is actually happening?

访问 http://localhost:1911/test.html  页面显示空白

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.88 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @farmfe/core: 1.3.15 => 1.3.15
```

**Comment by wre232114** [comment]
我们看看，感谢反馈
