### ISSUE TITLE
[Bug Report]: circular imports detected

### ISSUE THREAD

**Issue by remloyal** [farm-fe/farm#1807]
### Steps to reproduce

1. git clone https://github.com/remloyal/farm-demo.git
2. pnpm i
3. pnpm dev

### Reproduce link

https://github.com/remloyal/farm-demo.git

### What is actually happening?

Error:
```
[ Farm ] HMR invalidate: src/pages/HomePage.tsx. Not all exports of src/pages/HomePage.tsx are react components
```
It will be constantly updated, but the page remains unchanged

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500HX
    Memory: 5.08 GB / 31.73 GB
  Binaries:
    Node: 18.9.0 - F:\otherApp\Volta\tools\image\node\18.9.0\node.EXE
    Yarn: 1.22.19 - F:\otherApp\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 8.19.1 - F:\otherApp\Volta\tools\image\node\18.9.0\npm.CMD
    pnpm: 8.14.0 - F:\otherApp\Volta\bin\pnpm.EXE
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @farmfe/core: ^1.3.21 => 1.3.24
```

**Comment by wre232114** [comment]
It will be fixed in `@farmfe/core@1.3.26`. BTW, you can disable minify in dev which can reduce a half of the bootstrap time:
![image](https://github.com/user-attachments/assets/5714524a-3d48-406c-9066-e5865ba69fff)

Currently minify is enabled in both dev and prod.
