### ISSUE TITLE
[Bug Report]: 从 1.3.27 到 1.3.28 的更新导致 box-shadow 失效

### ISSUE THREAD

**Issue by Aloento** [farm-fe/farm#1830]
### Steps to reproduce

1. 在1.3.27 创建一个使用 https://tailwindcss.com/docs/box-shadow 的css div
2. 升级到1.3.28

### What is actually happening?

shadow 没了，完全不生效

### System Info

```Shell
"@farmfe/js-plugin-postcss": "^1.8.1",
    "postcss": "^8.4.47",
    "autoprefixer": "^10.4.20",
    "tailwindcss": "^3.4.14",
```

**Comment by wre232114** [comment]
我看一下
