### ISSUE TITLE
[Bug Report]: image url error when using SSR mode

### ISSUE THREAD

**Issue by dionfananie** [farm-fe/farm#1837]
### Steps to reproduce

i tried ssr development reference here: [react-ssr example](https://github.com/farm-fe/farm/tree/main/examples/react-ssr)

STP: 
- bun run build
- bun start

and the result of image is broken. somehow src isn't proper. 

<img width="1133" alt="Screenshot 2024-10-20 140156" src="https://github.com/user-attachments/assets/7b0bcb39-a53f-4753-8878-7b1d7c97fa85">

this is my package.json script
`"start": "farm start",
  "start:server": "farm watch --config farm.config.server.mjs",
  "watch": "farm watch --config farm.config.server.mjs",
  "build": "pnpm build:server && farm build",
  "build:server": "farm build --config farm.config.server.mjs",
  "preview": "node server.js"
  
  "dependencies": {
    "react": "18",
    "react-dom": "18",
    "react-router-dom": "^6.13.0",
    "express": "^4.18.2"
  },
  "devDependencies": {
    "@farmfe/cli": "^1.0.2",
    "@farmfe/core": "^1.3.0",
    "@farmfe/plugin-react": "^1.2.0",
    "@farmfe/plugin-sass": "^1.1.0",
    "@types/react": "18",
    "@types/react-dom": "18",
    "core-js": "^3.36.1",
    "react-refresh": "^0.14.0"
  }`

### What is actually happening?

the image url is error when develop using SSR mode 

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-13420H
    Memory: 4.43 GB / 7.63 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v18.19.1/bin/pnpm
    bun: 1.1.27 - ~/.bun/bin/bun
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.29
```

**Comment by wre232114** [comment]
I'll fix it
