### ISSUE TITLE
[Bug Report]: Set sourcemap to false, the program will encounter error issues after construction

### ISSUE THREAD

**Issue by stack-stark** [farm-fe/farm#1838]
### Steps to reproduce

1. pnpm create farm@latest
2. select vue3 template && pnpm install
3. farm.config.ts  set compilation: {sourcemap: false}
4. pnpm build && cd dist && http-server 
5.  Browser access http://127.0.0.1:8080

### What is actually happening?

The browser console error message is as follows:
index_4c07.e31c77c0.js:5 TypeError: u.then is not a function
    at index_4c07.e31c77c0.js:5:7878
    at Object.runWithContext (index_32d3.cc389144.js:5:28893)
    at L (index_4c07.e31c77c0.js:5:19109)
    at index_4c07.e31c77c0.js:5:23199

### System Info

```Shell
os：win11
node-v: v20.10.0
chrome-v: 127.0.6533.120
  "dependencies": {
    "vue": "^3.4.0"
  },
  "devDependencies": {
    "@farmfe/cli": "^1.0.2",
    "@farmfe/core": "^1.3.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "core-js": "^3.30.1"
  }
```

**Comment by wre232114** [comment]
I'll take a look
