### ISSUE TITLE
[Bug Report]: Farm Not working with Svelte 5.

### ISSUE THREAD

**Issue by JakubCzarlinski** [farm-fe/farm#1935]
### Steps to reproduce

1. `bun create farm@latest`
1. Select `svelte` template.
1. `cd farm-project`
1. `bun install` - this installs svelte 4
1. `bun run dev` - works
1. `bun install svelte@latest @sveltejs/vite-plugin-svelte@latest svelte-check@latest` - this installs svelte 5
1. `bun run dev` - this fails.
1. `bun run build && bun run preview` - this also fails.

Example:

https://github.com/JakubCzarlinski/farm-svelte-5-issue

### Reproduce link

https://github.com/JakubCzarlinski/farm-svelte-5-issue

### What is actually happening?

Updating to Svelte 5 errors on page render in both dev and prod build when using Farm.

### System Info

```Shell
System:
    OS: Linux 6.11 CachyOS Linux
    CPU: (24) x64 AMD Ryzen 9 7900 12-Core Processor
    Memory: 49.36 GB / 61.94 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.9.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
    bun: 1.1.34 - ~/.bun/bin/bun
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.33
```

**Comment by ErKeLost** [comment]
in svelte 5 you should change mount method
```ts
import App from './App.svelte';
import { mount } from 'svelte';
const app = mount(App, { target: document.getElementById("app") });
export default app;

```
and the latest vite plugin use some not support config in farm
we will fix it 

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/4ca0550f-156d-43c3-86af-a278d2f8ad32">

**Comment by JakubCzarlinski** [comment]
Ah my bad forgot about that. Thank you!
