### ISSUE TITLE
[Bug Report]: jose ReferenceError when targetEnv is library

### ISSUE THREAD

**Issue by ssttevee** [farm-fe/farm#1937]
### Steps to reproduce

1. create a new farm project
2. set `input: { index: "index.ts" }`
3. set `output: { targetEnv: "library" }`
4. install `jose` and import it
5. build the project

### What is actually happening?

```
ReferenceError: crypto$1 is not defined
```

There is actually a second error with partial bundling only with `targetEnv: "library"` where the import in the entrypoint is wrong:

Emitted: ```import { jwtVerify } from "main_dacd_js";```

But should be ```import { jwtVerify } from "main_dacd.4bf7e7ea.js";```

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.27 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 8.3.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.4
  npmPackages:
    @farmfe/core: ^1.3.33 => 1.3.33
```
```

**Comment by ssttevee** [comment]
The reference error still occurs with a single bundle

**Comment by ssttevee** [comment]
`library-node` does build and run properly for node, but I actually am trying to target browser.

Also, `jose` has different bundles for browser and node, so building for node will not run in browser. :(

**Comment by shulandmimi** [comment]
The `library-browser` issue has been fixed. You can download `@farmfe/core@1.3.34` and recompile the project. If you encounter new problems, please report them in time through issues

**Comment by ssttevee** [comment]
Thank you!
