### ISSUE TITLE
[Bug Report]: Using the officially recommended npm create farm@latest installation method, I initialized the project, but it unexpectedly failed to run

### ISSUE THREAD

**Issue by shendiid** [farm-fe/farm#1966]
### Steps to reproduce

1. npm create farm@latest
2. choose Vue

### What is actually happening?

import { DefaultLogger } from '@farmfe/core';
         ^^^^^^^^^^^^^
SyntaxError: The requested module '@farmfe/core' does not provide an export named 'DefaultLogger'    
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.15.0

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 849.72 MB / 15.94 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @farmfe/core: ^0.6.3 => 0.6.4
```

**Comment by ErKeLost** [comment]
try cleaning up the npm cache or install the latest verion of farm `@farmfe/core : '1.4.3'`, `@farmfe/cli : '1.0.4'`

**Comment by shendiid** [comment]
> try cleaning up the npm cache or install the latest verion of farm `@farmfe/core : '1.4.3'`, `@farmfe/cli : '1.0.4'`

I think **npm create farm@latest** should be immediately available and the latest version installed. Now I have upgraded @ farmfe/core and @ farmfe/cli, but it still doesn't work because I still need to install @ vite/plugin vue. Please check **npm create farm@latest** command.

**Comment by fu050409** [comment]
Aah I cannot reproduce this issue now. Are you sure you are using the correct `npm create farm@latest` and have not modified your `farm.config.ts`? The original auto gernerated `farm.config.ts` by `create-farm@latest` should be:

![image](https://github.com/user-attachments/assets/813958ad-a872-49d4-92b1-b85ad9bedc11)

And in `package.json` file, all dependencies are installed correctly on my local machine:

![image](https://github.com/user-attachments/assets/893fd1ff-4ece-40be-95e4-6cc0bf747ee4)

If you are sure that your commands are correct, consider checking your local environments. Feel free to add more infomation.

**Comment by ErKeLost** [comment]
your system info

```
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 849.72 MB / 15.94 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @farmfe/core: ^0.6.3 => 0.6.4
```
 @farmfe/core: ^0.6.3 => 0.6.4 this version to old

**Comment by shendiid** [comment]
The reason for this issue is that the version in my npm image AF repository is too low. Thank you guys.😂
