### ISSUE TITLE
[Bug Report]: path.extname function undefined

### ISSUE THREAD

**Issue by marsyusms** [farm-fe/farm#2000]
### Steps to reproduce

path.extname function undefined，在webpack中没有问题，farm中这个方法没定义，node 中有此方法定义
farm 代码
![image](https://github.com/user-attachments/assets/6693a11f-d800-4d3c-a02f-138dbbc4680d)
webpack
![image](https://github.com/user-attachments/assets/d9859f24-dd61-4ef8-ac2c-fb4ca35d6a8f)

### What is actually happening?

编译没有错误，运行时错误

### System Info

```Shell
windows 11
chrome
node v20.18.0
```

**Comment by shulandmimi** [comment]
看起来是运行在 浏览器中的，path 运行在浏览器中需要对应的 polyfill，webpack 以及 farm 你是如何处理的呢，麻烦贴下配置

**Comment by marsyusms** [comment]
在webpack中处理如下，在farm中确实没做处理，没有找到类似的配置示例：

const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

module.exports = {
	webpack: function (config) {
		config.resolve.fallback = {
			...config.resolve.fallback,
			path: require.resolve("path-browserify"),
		};
		return config;
	},
	plugins: [new NodePolyfillPlugin()],
};

**Comment by marsyusms** [comment]
以上配置解决了这个问题，感谢，问题可以关闭了
