### ISSUE TITLE
[Bug Report]: 开启treeShaking 后g2报错

### ISSUE THREAD

**Issue by 289420843** [farm-fe/farm#2019]
### Steps to reproduce

![PixPin_2024-12-23_15-15-53](https://github.com/user-attachments/assets/b6c4b8a3-60fc-48c8-a50b-a2cdb46a3919)

关闭treeShaking 或者 @farmfe/core 降级到 1.3.15 后正常

git clone https://github.com/289420843/farm-test.git
cd farm-test
npm install
npm run build
npm run preview
访问 http://localhost:1911/

### Reproduce link

https://github.com/289420843/farm-test.git

### What is actually happening?

.

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.84 GB / 31.93 GB
  Binaries:
    Node: 16.18.1 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - d:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - d:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @farmfe/core: 1.6.0 => 1.6.0
```

**Comment by fu050409** [comment]
目前懒加载和除屑功能不能同时启用，尝试设置`lazyCompilation: false`或者在`router/index.ts`中直接导入组件而不是异步导入

**Comment by 289420843** [comment]
> 目前懒加载和除屑功能不能同时启用，尝试设置`lazyCompilation: false`或者在`router/index.ts`中直接导入组件而不是异步导入

设置了lazyCompilation: false 还是有问题

**Comment by fu050409** [comment]
我们这边看看

**Comment by wre232114** [comment]
@289420843 试试 @farmfe/core@1.6.1
