### ISSUE TITLE
[Bug Report]:can not run example/vue

### ISSUE THREAD

**Issue by Zourunfa** [farm-fe/farm#204]
### Steps to reproduce

1.cd example/vue
2.pnpm i
3.pnpm start

at here, has an error :
![image](https://user-images.githubusercontent.com/51783403/232179821-47351843-7a72-4f47-a3f4-b0496073e48d.png)

### What is expected?

can build and  run vue project

### What is actually happening?

![image](https://user-images.githubusercontent.com/51783403/232179821-47351843-7a72-4f47-a3f4-b0496073e48d.png)

### System Info

```Shell

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.43 GB / 11.91 GB
  Binaries:
    Node: 18.13.0 - D:\nvm\v14.17.0\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566

```

**Comment by wre232114** [comment]
If you are building Farm from source, please run `pnpm bootstrap` under project root first

**Comment by Zourunfa** [comment]
ok  but  ocuur  #5

**Comment by ErKeLost** [comment]
Demo has been able to start successfully, and now it should be your problem with the protoc error report.
