### ISSUE TITLE
[Bug] : Run pnpm bootstrap has an error 

### ISSUE THREAD

**Issue by Zourunfa** [farm-fe/farm#206]
### Steps to reproduce

1.git clone ...
2.install protoc for windows
3.pnpm bootstrap

### What is expected?

pnpm bootstrap sucessfully

### What is actually happening?

error: failed to run custom build command for `sass-embedded v0.6.2`

Caused by:
  process didn't exit successfully: `D:\rust\farm\target\release\build\sass-embedded-7c5fc01480e11ead\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=ext/sass/sass-embedded.proto

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: PermissionDenied, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): (path: \"F:\\\\protoc-21.7-win64\\\\bin\"): 拒绝访问。 (os error 5)" }', C:\Users\47302\.cargo\registry\src\mirrors.tuna.tsiny\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\sass-embedded-0.6.2\build.rs:12:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

> @farmfe/plugin-sass@0.0.1 build D:\rust\farm\rust-plugins\sass
> napi build --platform --cargo-name farmfe_plugin_sass -p farmfe_plugin_sass --release

Internal Error: Command failed: cargo build --release -p farmfe_plugin_sass
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at BuildCommand.<anonymous> (D:\rust\farm\node_modules\.pnpm\@napi-rs+cli@2.10.0\node_modules\@napi-rs\cli\scripts\index.js:31968:26)
    at Generator.next (<anonymous>)
    at fulfilled (D:\rust\farm\node_modules\.pnpm\@napi-rs+cli@2.10.0\node_modules\@napi-rs\cli\scripts\index.js:3490:58)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.43 GB / 11.91 GB
  Binaries:
    Node: 18.13.0 - D:\nvm\v14.17.0\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
```

**Comment by ErKeLost** [comment]
This may be a matter of your authority.

- You can try to run vscode as an administrator
- Look at this error report. F:\ protoc-21.7-win64\ bin this directory does not have permission to access you can try to install to an accessible path

You can try it.

**Comment by Zourunfa** [comment]
1.![image](https://user-images.githubusercontent.com/51783403/232216652-73a4cf57-a8b6-4c60-aa30-e1b8f027f0c7.png)
2.
![image](https://user-images.githubusercontent.com/51783403/232220629-86976648-8ec9-4385-8e16-df42d1de10c3.png)
![image](https://user-images.githubusercontent.com/51783403/232220987-e6124b5d-f571-484c-8029-e0965fcbda30.png)
3.
![image](https://user-images.githubusercontent.com/51783403/232221790-dcdbf84f-7dbf-44a1-9f88-af45c524ebb0.png)
vscode 和mysql命令都能运行 应该是有权限的

@farmfe/plugin-sass@0.0.1 build D:\rust\farm\rust-plugins\sass 上面报错 是不是这个包的问题 我需要怎么做

**Comment by Zourunfa** [comment]
而且我每次pnpm bootstrap  至少要10分钟，切换了不同的npm源 也是 ，一般需要这么久吗
![image](https://user-images.githubusercontent.com/51783403/232222492-b4fdec14-99c2-45cc-b9cc-d74235cdafe6.png)

**Comment by callqh** [comment]
Maybe you can refer to this issue https://github.com/ahabhgk/sass-embedded-host-rust/issues/44

**Comment by Zourunfa** [comment]
![image](https://user-images.githubusercontent.com/51783403/232225538-c63db822-c939-432d-98b3-1882a23c6bce.png)
意思是  我是要把这句话加在代码中吗

> Maybe you can refer to this issue [ahabhgk/sass-embedded-host-rust#44](https://github.com/ahabhgk/sass-embedded-host-rust/issues/44)

**Comment by Zourunfa** [comment]
I've looked at all the related issues, and I don't seem to have found a solution 
https://github.com/tokio-rs/prost/issues/830
https://github.com/web-infra-dev/rspack/issues/2490
https://github.com/ahabhgk/sass-embedded-host-rust/issues/44
![image](https://user-images.githubusercontent.com/51783403/232226245-21ac1ed2-7462-44d0-92db-2066127303ba.png)
Is there no way to solve it now? What do I need to do？

**Comment by callqh** [comment]
If the reply under this[ issue ](https://github.com/ahabhgk/sass-embedded-host-rust/issues/44)doesn't solve your problem, we don't have a good solution, because it seems to be a problem with the path not having permission to access

**Comment by Zourunfa** [comment]
ok thanks

**Comment by ErKeLost** [comment]
你尝试一下 卸载了重新安装呢，或者你换一个盘 那个报错确实就是没有权限访问，我刚也试了一下在windows上卸载重新安装也是没有问题的，你可以尝试一下 ，我们目前都没有遇到这个问题

**Comment by callqh** [comment]
Perhaps you can also try restarting the computer?
Windows system reboot can solve 99% of the problems (:

**Comment by Zourunfa** [comment]
> You try to uninstall and reinstall, or if you change the directory, you should have no permission to access the error. I just tried to uninstall and reinstall on windows. There is no problem with it. You can give it a try. We haven't encountered this problem at present.
thanks，  I placed it under C: \Program Files and successfully
