### ISSUE TITLE
resolve bug

### ISSUE THREAD

**Issue by ysy945** [farm-fe/farm#214]
### Steps to reproduce

- 第一个bug
1. 使用node的第三方库
2. 第三方库的package.json文件的main字段没有很精确 例如:实际文件是lib/index.js 但是main字段写的lib farm牛读取不到这个第三方库的入口文件。
<img width="556" alt="image" src="https://user-images.githubusercontent.com/79794654/232309174-69d6d78d-14c4-460c-aab5-144dc4a7c5f0.png">

- 第二个bug
1. 库内使用了一些特殊的引入包名,例如:"#xxx"、"@xxx"。并且这个文件在package.json中配置了import字段。
<img width="399" alt="image" src="https://user-images.githubusercontent.com/79794654/232309651-ff772bdd-8286-4fed-b5f4-2fc8d680f3d0.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/79794654/232309711-14fbdc04-c068-4182-a756-bfef82068653.png">

### What is expected?

正确解析package.json文件 以及包路径 

### What is actually happening?

读不到第三方包的内容
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/79794654/232309802-8cbdfb90-149e-4a6c-aa74-01db28ce0b9a.png">

### System Info

```Shell
none
```

**Comment by ErKeLost** [comment]
第一个应该是有问题 ，这种情况没考虑到，第二个应该解决了呢，这是chalk在哪里使用的，我去试一下

**Comment by wre232114** [comment]
我解决下第一种情况

**Comment by ysy945** [comment]
第二个应该是我没升级版本。现在好了
