### ISSUE TITLE
pnpm 7以上不支持。

### ISSUE THREAD

**Issue by tzwhyqq** [farm-fe/farm#220]
### What problem does this feature solve?

使用 pnpm 8.1.x 版本 安装不了依赖看了好像版本锁定7

### What does the proposed API look like?

pnpm 8以上版本支持

**Comment by wre232114** [comment]
是的，目前是锁定了 7。后续会升级到 8，可以暂时用 pnpm 7 安装依赖

**Comment by wre232114** [comment]
已经把 pnpm 版本升级到 8 了，同步下 main 的代码就可以了

**Comment by tzwhyqq** [comment]
ok
