### ISSUE TITLE
pnpm8打包反馈错误信息

### ISSUE THREAD

**Issue by tzwhyqq** [farm-fe/farm#222]
### Steps to reproduce

pnpm install

### What is expected?

 Error: Expected "0.15.18" but got "0.14.49"
│     at validateBinaryVersion (D:\TestProject\farm-fe\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.15.18\node_modules\esbuild\install.js:94:11)
│     at D:\TestProject\farm-fe\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.15.18\node_modules\esbuild\install.js:241:5

### What is actually happening?

打包报错，这个不知道是farm 的问题还是依赖的问题。

### System Info

```Shell
win10
node 18
vue3.2
```

**Comment by wre232114** [comment]
依赖的问题，镜像源有问题，用 npm 官方的镜像源看看
