### ISSUE TITLE
@路径问题

### ISSUE THREAD

**Issue by tzwhyqq** [farm-fe/farm#227]
### What problem does this feature solve?

使用farm 搭建 项目的时候 ，发现 import { defHttp } from '@/utils/http/axios' 这样的识别不了，
报错信息
Potential Causes:
1.The file that `@/locales/setupI18n` points to does not exist.
2.Install it first if `@/locales/setupI18n` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.
3. If `@/locales/setupI18n` is a alias, make sure your alias config is correct.

还是我需要哪里配置（vite里面是没问题）。

### What does the proposed API look like?

希望能够支持这样导入

**Comment by wre232114** [comment]
在配置文件里面，配置 resolve.alias

**Comment by tzwhyqq** [comment]
关闭
