### ISSUE TITLE
Config compiler resolves to "browser" main field

### ISSUE THREAD

**Issue by oblador** [farm-fe/farm#234]
### Steps to reproduce

Have a module with the following `package.json` where `main.js` imports `sub.js`:

```json
{
  "name": "resolution-example",
  "version": "1.0.0",
  "main": "main.js",
  "browser": {
    "./sub.js": "./browser.js"
  }
}
```

### What is expected?

Importing `resolution-example` in `farm.config.ts` will yield contents of `sub.js`.

### What is actually happening?

Importing `resolution-example` in `farm.config.ts` will yield contents of `browser.js`.

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    Yarn: 1.22.17 - ~/.asdf/shims/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 107.0.1
    Safari: 16.4
  npmPackages:
    @farmfe/core: latest => 0.6.3
```

**Comment by wre232114** [comment]
I tried this example and it works as expected, the package `resolution example` always exports `main.js`, and `main.js` imports `sub.js` and the `./sub.js` is replaced by `./browser.js`.

So the actually result is: `farm.config.ts` -> `main.js` -> `browser.js`

**Comment by oblador** [comment]
Exactly, but it shouldn't be replaced with `browser.js` for the config as the target is node, not browser.

**Comment by oblador** [comment]
I messed up in the issue description, updated now.

**Comment by wre232114** [comment]
I see, by default, the target is browser and it is not configurable for now, I will support it today
