### ISSUE TITLE
[Feature]: dev server ws port conflict and injection

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#288]
### What problem does this feature solve?

Solve the problem of port conflict and injection under multiserver

port conflicts need to be prevented when starting multiple servers at the same time

It is recommended that websocket and devserver use the same port for output

devserver and websocket prot conflict
devserve and ws use same port cause complate code
Injecting environment variables to listen for client ws hmr updates

### What does the proposed API look like?

none

**Comment by wre232114** [comment]
I think for your case, you just need to config `server.port` in the configuration.

**Comment by wre232114** [comment]
For now they can not be the same port, you may need to export two ports if you want to develop on a remote server. 

HMR port can be configured by `server.hmr.port`.

**Comment by wre232114** [comment]
> Hi, just a quick check on this issue to make sure i understand it correctly:
> 
> > It is recommended that websocket and devserver use the same port for output
> 
> The hmr port and dev server port are currently hardcoded as 9801 and 9000. Does this feature suggest that ideally they should be started on the same port by default? And when opening another set of dev server + hmr, they should also use the same port (say, 9001)?

The dev server and ws server is different server, they can't listen for the same port I think.

**Comment by ErKeLost** [comment]
Two ways that can be adopted at present: 
1. Start a `http server` to determine port access before the hmr plugin hook is registered. If there is a `port conflict`, the `port + +`
2. We can get part of the configuration file and start devserver first to determine `port conflicts` (instead of creating a http to determine), and then compile (this method requires an attempt to load the browser, but the compilation is not complete, or we can not let the user feel that we have started the service and wait for the compilation to complete before entering the result in `node`).

Server port and hmr port are recommended to use the same port if the user does not set the specified port.
