### ISSUE TITLE
Segmentation fault on Macbook m1 chip

### ISSUE THREAD

**Issue by jiesia** [farm-fe/farm#295]
### Steps to reproduce

```bash
pnpm start
```

When i exec the command above, takes error:
```bash
[ Farm ] Using config file at /Users/jess/Code/Jess/farm-project/farm.config.ts
[1]    30907 segmentation fault  npx farm start
```

And it also don't work for `pnpm build`.

### What is expected?

build

### What is actually happening?

segmentation fault

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.5.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.2
  npmPackages:
    @farmfe/core: ^0.6.3 => 0.6.3
```

**Comment by ErKeLost** [comment]
The reason for the startup failure is due to the plug-in version dependency problem. Because of pnpm v8, we cannot use * or latest to set the latest version number, resulting in the project startup failure.

**Comment by jiesia** [comment]
It works, thanks!
