### ISSUE TITLE
[Bug Report][0.7.3]: Error report of vue template construction product

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#307]
### Steps to reproduce

example/vue

```ts
// step 1
pnpm build

// step 2
pnpm preview
```

### What is expected?

normal

### What is actually happening?

![image](https://github.com/farm-fe/farm/assets/66500121/69a0a9bb-c5bb-4ec8-9222-867e78eaf63c)

![image](https://github.com/farm-fe/farm/assets/66500121/289ae2a2-364e-45ff-952d-555d4c8e5dd1)

### System Info

```Shell
windows 11
```

**Comment by wre232114** [comment]
This bug comes for the js plugin vue. The HMR code should not present in prod, I will fix it
