### ISSUE TITLE
[Bug Report][0.7.3]: Failure of build product compilation css

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#308]
### Steps to reproduce

example/react

```ts
// step 1
pnpm build

// step 2
pnpm preview
```

### What is expected?

normal

### What is actually happening?

Normal situation

```ts
pnpm start
```

![image](https://github.com/farm-fe/farm/assets/66500121/30318072-eded-40ad-ae2e-66d6e6b6a7ee)

![image](https://github.com/farm-fe/farm/assets/66500121/b9d9d7e9-f375-48fa-a50b-6b9417186608)

Error situation

```ts
pnpm build

pnpm preview
```

![image](https://github.com/farm-fe/farm/assets/66500121/f8ebb64f-9eb6-49b9-97b2-28bf8c77ebb9)

### System Info

```Shell
windows 11
```

**Comment by wre232114** [comment]
This is caused by the wrong order of the css resource. It should be topo order but it's not for now. It's a bit complex, I will fix it later
