### ISSUE TITLE
[Bug Report][0.8.10]: process be killed

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#390]
### Steps to reproduce

`example/css-modules`

The process of starting the project was killed and occasionally repeated. I'm not sure if it's the problem of farm.

### What is expected?

normal

### What is actually happening?

![image](https://github.com/farm-fe/farm/assets/66500121/04132742-0b39-41d3-bf55-f2eefe556e2f)

### System Info

```Shell
mac
```

**Comment by wre232114** [comment]
I can not reproduce this issue on my mac. Do you execute `pnpm bootstrap`?

**Comment by ErKeLost** [comment]
Maybe my mac caused the problem.
