### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by csfankun** [farm-fe/farm#403]
### Steps to reproduce

1、npm i --save @farmfe/js-plugin-less
2、farm.config.ts config just as  
```js
import type { UserConfig } from '@farmfe/core';
import Less from '@farmfe/js-plugin-less'; //  import the plugin

export default <UserConfig>{
  plugins: [
    '@farmfe/plugin-react',
    Less({
      // custom options here
    }),
  ],
};
```
3、 In main.tsx import any less file and write some css code.

4. run `npm run start` You will see cannot find module less

### What is expected?

no error 

### What is actually happening?

Cannot find module 'less'

### System Info

```Shell
windows
```

**Comment by ErKeLost** [comment]
![image](https://github.com/farm-fe/farm/assets/66500121/752d565e-8799-4793-a5dc-bbfb41e18c85)
![image](https://github.com/farm-fe/farm/assets/66500121/01a97356-6874-4e38-afa7-00f7e75b8f4a)
