### ISSUE TITLE
Farm 1.0.0-beta

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#464]
### What problem does this feature solve?

Farm has implement most expect features, there are only a few features to be completed to make Farm 1.0. Farm will release 1.0.0-beta when following features are implemented:

#460 
#457 
#119 
#115 
#463

**Comment by ErKeLost** [comment]
#431

**Comment by ErKeLost** [comment]
Farm will be released at the end of 2023. 1.0-beta needs to complete the following features before that.

- **Persistent cache:** cache the build product to disk and reuse it in multiple builds to further speed up the cold start of the project.

- **90% Vite plugins are compatible:** compatible with generate stage hooks, 90% Vite plug-ins can seamlessly connect to Farm.

- **Dx:** enhance user experience error handling server starts, build progress bar

**Comment by exoticknight** [comment]
Now it's February 2024, but the official website's Chinese version still has many errors and placeholders.

**Comment by ErKeLost** [comment]
hi @exoticknight  We are already in the process of revising the document. 1.0beta and complete English and Chinese documents will be available this month.
