### ISSUE TITLE
Comparison with Turbopack

### ISSUE THREAD

**Issue by Shomvel** [farm-fe/farm#48]
Turbopack is a build tool created by Vercel. It's also written in Rust. How does farm compare with Turbopack?

**Comment by wre232114** [comment]
I'll try to construct a benchmark project that supports turbopack later.

**Comment by Shomvel** [comment]
Evan you did a benchmark comparing Vite and Turbopack: [vite-vs-next-turbo-hmr](https://github.com/yyx990803/vite-vs-next-turbo-hmr). Hope it may be of help :)

**Comment by wre232114** [comment]
Thanks.

**Comment by wre232114** [comment]
@Shomvel see https://github.com/farm-fe/performance-compare
