### ISSUE TITLE
Support react runtime & ImportSource

### ISSUE THREAD

**Issue by FairyScript** [farm-fe/farm#489]
### What problem does this feature solve?

What problem does this feature solve?

Currently, Some css-in-js lib (like @emotion) needs to use ImportSource to inject the runtime. Exposing [the SWC configurations](https://swc.rs/docs/configuration/compilation#jsctransformreactruntime) regarding React Runtime & ImportSource could provide more flexibility and better customization to developers who use both farm and emotion.

By supporting this feature, users will have more options to handle React's runtime and transform JSX according to specific needs and requirements.

Ideally developers should be allowed to fill in two option properties:

`react.runtime`: for setting the runtime. Possible values can be either `automatic` or `classic`.
`react.importSource`: for setting the ImportSource to inject the runtime. Users should be allowed to input any string that represents the import source.

Thank you for considering our request. Any suggestions and feedback would be much appreciated.

### What does the proposed API look like?

```js
{
  compilation: {
    script:{
      // keep consistent with SWC
      react:{
        runtime: 'automatic',
        importSource: '@emotion/react',
      },
    },
    // ...
  },
}
```

**Comment by wre232114** [comment]
The `react` is configured by `@farmfe/plugin-react`, for example:
```ts
export default defineConfig({
  // ..
  plugins: [
    ['@farmfe/plugin-react', { runtime: 'automatic',  importSource: '@emotion/react' }]
  ]
});
```

**Comment by FairyScript** [comment]
Thanks for your prompt response!
Where can I read the full document of @farmfe/plugin-react?

**Comment by wre232114** [comment]
The document is still under construction.

**Comment by FairyScript** [comment]
got it.😄

**Comment by maczyt** [comment]
> The `react` is configured by `@farmfe/plugin-react`, for example:
> 
> ```ts
> export default defineConfig({
>   // ..
>   plugins: [
>     ['@farmfe/plugin-react', { runtime: 'automatic',  importSource: '@emotion/react' }]
>   ]
> });
> ```

I got an error `Invalid Config: the config object does not have field name`. How can I configure it?
