### ISSUE TITLE
[Feature]: Websocket services and http services share a set of ports

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#544]
### What problem does this feature solve?

The first problem encountered at present:

Because users may run different numbers of services locally and configure different host during dev development, this will cause port conflicts and cause websocket services to report errors.

The current solution is to switch websocket ports in the case of port conflicts, which will lead to port conflicts under different host, which cannot be monitored.

The second question：

The service determines that the location of the conflict is incorrect. It should do this after merging the server configuration rather than getting the userconfig. This will result in incomplete or empty server configuration, error.

And it can also reduce the port footprint when running on similar docker.

### What does the proposed API look like?

Two sets of services share the same port

**Comment by FairyScript** [comment]
In this PR #546 , when `hmr.port` is unconfiged, the hmr server will use `server.port`. i think this partly solves the problem.

> https://github.com/FairyScript/farm/blob/829e34cc8b128de7a5a571786b2eb32d886fae3e/packages/core/src/config/index.ts#L310-L313
