### ISSUE TITLE
[create-cli] The `-- template` parameter was not passed in correctly

### ISSUE THREAD

**Issue by RSS1102** [farm-fe/farm#558]
### Steps to reproduce

```
npm create farm@latest my-vue-app -- --template vue
```

### What is expected?

Create a farm vue project directly

### What is actually happening?

The template type option is still displayed

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.26 GB / 13.86 GB
  Binaries:
    Node: 18.12.1 - E:\node\node.EXE
    Yarn: 1.22.19 - E:\node\yarn.CMD
    npm: 9.8.0 - E:\node\npm.CMD
    pnpm: 8.6.9 - E:\node\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (116.0.1938.81)
    Internet Explorer: 11.0.22621.1
```

### Any additional comments?

![image](https://github.com/farm-fe/farm/assets/81673017/2cd5ca92-4f3d-4131-b6a8-758635973759)

**Comment by Nirvana-Jie** [comment]
It may be an exception in command line argument parsing
