### ISSUE TITLE
[Feature]: make `farm` the ability to access with `unplugin`

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#567]
### `Reason`

The framework of unplugin that has been connected (or is about to be connected to bun).
![image](https://github.com/farm-fe/farm/assets/66500121/1c29a16f-38a8-4df3-ba6a-b1b30b585f1b)

### At present, the hooks that farm can do is as follows (it has passed the unplugin test), up to now, farm can basically access unplugin.

![image](https://github.com/farm-fe/farm/assets/66500121/0ecd65a9-84de-424d-8c29-0e4e522dd3b4)
![image](https://github.com/farm-fe/farm/assets/66500121/8cc5b00e-da18-4157-b321-3343024797e6)

The following `loadInclude` `load` `transformInclude` `transform` `witeBundle`(call `finish` in farm) can be used directly

After the access, the following problems were exposed.

- `loadInclude` `transformInclude` regular expressions and boolean formats return value are not supported

### In Unplugin 

![image](https://github.com/farm-fe/farm/assets/66500121/5c6fbbca-9195-4e1a-8614-62f1bb199f60)

### In Farm

![image](https://github.com/farm-fe/farm/assets/66500121/12df1e41-492e-4104-9d10-2d4fb2fa22b6)

Although we can smooth out structural differences through some callbacks, our return to regularities and statements is inflexible.

Could make devastating changes to our existing framework and plugins.

- Whether to add other hooks

We need to consider whether to support other hooks.
We can do some unique hooks through our custom hook callback.
But do we consider supporting other hook functions in order to be compatible with some other ecology?
Finally achieve the out of the box mode.
e.g: 
[resolveId](https://rollupjs.org/guide/en/#resolveid)
[buildStart](https://rollupjs.org/guide/en/#buildstart)
[buildEnd](https://rollupjs.org/guide/en/#buildend)
[watchChange](https://rollupjs.org/guide/en/#watchchange)

@wre232114  Please refer to

### What does the proposed API look like?

[all hooks](https://github.com/unjs/unplugin#hooks)

**Comment by wre232114** [comment]
`resolveId`, `buildStart`, `buildEnd`, `watchChange` are already supported
