### ISSUE TITLE
[Feature Request]: `Output.filename` that can be modified

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#570]
### Steps to reproduce

<img width="1558" alt="image" src="https://github.com/farm-fe/farm/assets/66500121/4e00c985-6ca8-4f91-b7a2-c8584cb31cf2">

```ts
output.filename: Default value "[resourceName].[ext]"
```
Do we allow you to change the output file name?

### What is expected?

normal

### What is actually happening?

none

### System Info

```Shell
none
```

**Comment by wre232114** [comment]
try `entryFileName`, see https://farm-fe.github.io/docs/config/farm-config#outputentryfilename
