### ISSUE TITLE
[Bug Report]: Some problems of arco pro example

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#603]
### Steps to reproduce

- ###  Load svg error

```
pnpm dev
```

file path 
```
src/pages/dashboard/workplace/overview.tsx
```

![image](https://github.com/farm-fe/farm/assets/66500121/a364246b-f448-43f8-906f-f8abd3c5ec31)

Direct use of svg components should not report an error

- ### An error report leads to a blank screen

![image](https://github.com/farm-fe/farm/assets/66500121/bd994718-d3a5-4f87-83ab-bc17ce0f9046)

![image](https://github.com/farm-fe/farm/assets/66500121/ee41a643-83e7-405b-9048-270765c85a88)

By default, there is also an empty array. I don't know why this place caused an error because of the poor behavior of our plugins.

I think there are two problems here.

1. The wrong report of the first problem leads to a blank screen.
2. The second question, I don't think this method should report an error.

- ### Hmr duplicate enrollment problem

![6c94d05151ce1f6bef366ad8de8aae6](https://github.com/farm-fe/farm/assets/66500121/c4473eab-e6c7-4985-a587-48a40fc79268)

can compare the startup of rspack. The current example has added the comparison of farm and rspack.

### What is expected?

normal

### What is actually happening?

none

### System Info

```Shell
none
```

**Comment by wre232114** [comment]
Another issue: css are not minified during build
