### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#607]
### What problem does this feature solve?

Support comments with 3 config options：
1. licence: preserve all licence comments
2. none: remove all comments
3. all: preserve all comments

### What does the proposed API look like?

```ts
export default {
   compilation: {
        comments: 'license', // 'licence', 'none', 'all'
   }
}
```

**Comment by faga295** [comment]
Hey @wre232114 , I‘ve supported [extract comments](https://github.com/web-infra-dev/rspack/pull/2882) in rspack before, maybe I can help to support it

**Comment by wre232114** [comment]
That's great! We don't have time to support it yet, you can help to support it
