### ISSUE TITLE
[bug]:Unable to inject CSS variables correctly in Vue single file

### ISSUE THREAD

**Issue by RSS1102** [farm-fe/farm#608]
### Steps to reproduce

![image](https://github.com/farm-fe/farm/assets/81673017/18aa7e46-4e62-46ac-abd2-222dc0cb8a36)

### What is expected?

in vite:
![image](https://github.com/farm-fe/farm/assets/81673017/7d091613-79d2-4bc5-be40-ff91024f5ae9)

### What is actually happening?

in farm
![image](https://github.com/farm-fe/farm/assets/81673017/4839826a-21df-411b-8e4d-4fa9d12b575c)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 810.57 MB / 13.86 GB
  Binaries:
    Node: 18.12.1 - E:\node\node.EXE
    Yarn: 1.22.19 - E:\node\yarn.CMD
    npm: 9.8.0 - E:\node\npm.CMD
    pnpm: 8.7.6 - E:\node\pnpm.CMD
  Browsers:
    Edge: Chromium (117.0.2045.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @farmfe/core: ^0.12.11 => 0.12.11
```

**Comment by wre232114** [comment]
fixed in @farmfe/js-plugin-vue@2.0.2
