### ISSUE TITLE
Cannot find module '@farmfe/core-win32-ia32-msvc'

### ISSUE THREAD

**Issue by Zcxxxx** [farm-fe/farm#637]
### Steps to reproduce

1. yarn create farm
2. yarn start

### What is expected?

no throw errors

### What is actually happening?

throw Error: Cannot find module '@farmfe/core-win32-ia32-msvc'。
npm website can't search this library
![error](https://github.com/farm-fe/farm/assets/60350925/db1599b6-f08f-4873-a16c-429a05d63696)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) ia32 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 5.46 GB / 15.65 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files (x86)\nodejs\npm.CMD
    pnpm: 7.30.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.22621.2283.0), Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
```

**Comment by wre232114** [comment]
Currently Farm only supports following  4platforms:
1. darwin-arm64
2. darwin-x64
3. linux-x64-gnu
4. win32-x64-msvc

`win32-ia32-msvc` will be supported later.

**Comment by Zcxxxx** [comment]
ok thanks，go for it！
