### ISSUE TITLE
[Bug] Starting in the upper directory, postcss plugin  will not work

### ISSUE THREAD

**Issue by NidMo** [farm-fe/farm#642]
### Steps to reproduce

1. in upper directory
2. farm start -c  xxxx/xxx/farm.config.ts

### What is expected?

Normal startup

### What is actually happening?

 Build failed due to errors: 

 [@farmfe/js-plugin-postcss] TypeError: Cannot read properties of undefined (reading 'config')

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 53.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
    pnpm: 8.6.2 - ~/.nvm/versions/node/v16.14.0/bin/pnpm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 118.0.5993.70
    Edge: 118.0.2088.57
    Safari: 17.0
```

**Comment by ErKeLost** [comment]
Add a problem: setting configpath causes the root path to be modified as well

![image](https://github.com/farm-fe/farm/assets/66500121/00203ff5-e035-43d5-9dc5-4d000d8d994c)

**Comment by wre232114** [comment]
Is this issue fixed?

**Comment by ErKeLost** [comment]
This issues temporarily shuts down the error occurs within tailwind farm configuration responds consistently under different conditions, but tailwind internal error report
