### ISSUE TITLE
scss moudle not support in Vue3?

### ISSUE THREAD

**Issue by toplyb** [farm-fe/farm#645]
### Steps to reproduce

I got an error whit "Error: Preprocessor dependency "sass" not found. Did you install it?" when i was useing scss in Vue3. But i already have the '@farmfe/plugin-sass' plugin installed. 
It is was not successed when i remove `scope`.
The code is as follows
```vue
<template>
  <div class="header">
  </div>
</template>

<style scoped lang='scss'>
.header {
  height: 10vh;
  box-shadow: 0 7px 5px -5px #fff;
}
</style>
```
the error:
[scss-(error)]:"Error: Preprocessor dependency "sass" not found. Did you install it?"
[ Farm ] Error: Can not load xxx.vue. Original error:
Some(NAPIError("Cannot read properties of undefined (reading 'scoped')\nTypeError: Cannot read properties of undefined (reading 'scoped')\n    at executor (xxx/node_modules/@farmfe/js-plugin-vue/build/index.cjs:976:47)")).

### What is expected?

It will be support `scss` in Vue3

### What is actually happening?

It was not support `scss` in `Vue3`

### System Info

```Shell
MacBook Pro 13.0.1
Chrome 118
```

**Comment by wre232114** [comment]
You should install `sass` in your project. for example:
```bash
pnpm add sass -D
```

**Comment by ErKeLost** [comment]
Do you have the `sass` package installed

I didn't reproduce your mistake.

You can try to use the plugin demo address of vite https://github.com/farm-fe/farm/tree/main/examples/vite-adapter-vue

**Comment by toplyb** [comment]
> You should install `sass` in your project. for example:
> 
> ```shell
> pnpm add sass -D
> ```

~ Eh.. I am terribly sorry. I did forget to install `sass`. Thanks!

**Comment by toplyb** [comment]
> Do you have the `sass` package installed
> 
> I didn't reproduce your mistake.
> 
> You can try to use the plugin demo address of vite https://github.com/farm-fe/farm/tree/main/examples/vite-adapter-vue

🤣 I did forget to install `sass`. Thanks!
