### ISSUE TITLE
[@farmfe/js-plugin-sass transform Error] Error: Can't find stylesheet to import. 

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#681]
### Steps to reproduce

@forward 'element-plus/theme-chalk/src/mixins/config.scss' with ($namespace: 'ep'
);

### What is expected?

Compilation passed

### What is actually happening?

![image](https://github.com/farm-fe/farm/assets/35885819/23b13f0f-bba3-4948-88c6-1a0c7de039a7)

### System Info

```Shell
Win10
```

**Comment by wre232114** [comment]
fixed in `@farmfe/js-plugin-sass@2.1.1`. Also, you can try `@farmfe/plugin-sass` which is a Rust plugin and maybe faster than the js plugin sass
