### ISSUE TITLE
thread '<unnamed>' panicked at 'can not find resource

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#683]
### Steps to reproduce

![image](https://github.com/farm-fe/farm/assets/35885819/17e68127-9e13-4614-94d3-792f83c71d97)

![image](https://github.com/farm-fe/farm/assets/35885819/1e9eb949-194d-438a-9466-eb997847b222)

Is this a bug? How can i use svg in vue style tag?

### What is expected?

Load svg correctly

### What is actually happening?

thread '<unnamed>' panicked at 'can not find resource: resolving "@/assets/svg/exception/404.svg" for ModuleId { relative_path: "src/views/sys/404.vue", query_string: "?vue&type=style&index=0&scoped=aa1eef2d&lang.scss" }', crates\plugin_css\src\source_replacer.rs:52:13 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### System Info

```Shell
Win10
```

**Comment by wre232114** [comment]
What version of `@farmfe/core` you used?  and Do you configure `compilation.resolve.alias`? Above code seem to work fine in our examples/vite-adapter-vue

**Comment by YLMC2017** [comment]
I am migrating old vite projects，remove vite-svg-loader plugin then is work fine.

**Comment by wre232114** [comment]
I see. thanks for supporting farm
