### ISSUE TITLE
Support .env file, env-variables

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#684]
### What problem does this feature solve?

Support .env file, env-variables

### What does the proposed API look like?

like https://vitejs.dev/guide/env-and-mode.html#env-variables

**Comment by wre232114** [comment]
Env has supported. see https://github.com/farm-fe/farm/blob/main/examples/env/farm.config.mjs

**Comment by YLMC2017** [comment]
Okay, this configuration was not found in the documentation.

**Comment by wre232114** [comment]
> Okay, this configuration was not found in the documentation.

@ErKeLost cc

**Comment by ErKeLost** [comment]
@YLMC2017  I'd like to supplement the file now.
