### ISSUE TITLE
Error: Parse `node_modules/.pnpm/element-plus@2.4.1_vue@3.3.7/node_modules/element-plus/theme-chalk/src/upload.scss` failed.

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#688]
### Steps to reproduce

![image](https://github.com/farm-fe/farm/assets/35885819/0adf2432-844b-4b1c-9fa0-736a097ea6d9)

https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/upload.scss

### What is expected?

Compilation passed

### What is actually happening?

Error: Parse `node_modules/.pnpm/element-plus@2.4.1_vue@3.3.7/node_modules/element-plus/theme-chalk/src/upload.scss` failed.
   Error:
    × Expected Declaration value
      ╭─[node_modules/.pnpm/element-plus@2.4.1_vue@3.3.7/node_modules/element-plus/theme-chalk/src/upload.scss:29:1]
   29 │   top: 0;
   30 │   left: 0;
   31 │   opacity: 0;
   32 │   filter: alpha(opacity=0);
      ·                        ─
   33 │ }

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.19 GB / 15.79 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @farmfe/core: ^0.13.16 => 0.13.16
```

**Comment by wre232114** [comment]
SWC does not support this syntax cause it is not standard, see. https://github.com/swc-project/swc/issues/6025.

In Farm, you can write a plugin to ignore it, for examples:
```ts
// farm.config
export default {
  plugins: [
      {
          name: 'remove-css-filter-plugin',
          transform: {
              filter: {
                  resolvedPaths: ['node_modules/element-plus/theme-chalk/src/upload.scss']
              },
              executor({ content }) {
                  return {
                      content: content.replace('filter: alpha(opacity=0);', ''),
                  }
              }
          }
      }
  ]
}
```
