### ISSUE TITLE
[help wanted] how to use postcss and css module together

### ISSUE THREAD

**Issue by niuiic** [farm-fe/farm#693]
### Steps to reproduce

```
git clone https://github.com/niuiic/gallery
pnpm i
pnpm add -D @farmfe/core@0.13.16 -w
pnpm dev --filter layout
```

Check `gallery/apps/layout`

I found out that I probobaly have to set `filter` option for `@farm-fe/js-plugin-postcss`,or it would never work, but haven't found a correct value.

### What is expected?

![image](https://github.com/farm-fe/farm/assets/63799565/ed3b31fb-bea4-4950-9cca-937901fe697d)

`height: 100px` should be transformed to `height: calc(100 * var(--unit-length))`

BTW, who add the prefix for `box-sizing`? (not `@farmfe/plugin-sass` or `@farmfe/js-plugin-postcss`)

### What is actually happening?

custom postcss plugin not work

### System Info

```Shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 10.92 GB / 15.59 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/node
    npm: 9.8.1 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/npm
    pnpm: 8.10.0 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/pnpm
  npmPackages:
    @farmfe/core: ^0.13.16 => 0.13.16 
```
```


### Any additional comments?

_No response_

**Comment by wre232114** [comment]
I'll take a look
