### ISSUE TITLE
Supports importing multiple modules from the file system

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#698]
### What problem does this feature solve?

Supports importing multiple modules from the file system
like vite import.meta.glob or webpack require.context

### What does the proposed API look like?

https://vitejs.dev/guide/features.html#glob-import

**Comment by wre232114** [comment]
it is already supported.

**Comment by YLMC2017** [comment]
> it has already supported. just use `import.meta.glob` like vite

Do you have any specific examples? I didn't find them in the document.

**Comment by wre232114** [comment]
I will add it to the document today

**Comment by YLMC2017** [comment]
> I will add it to the document today. see the test cases https://github.com/farm-fe/farm/blob/main/crates/swc_transformer_import_glob/tests/fixtures/default_glob/input.js.
> 
> It's just the same as vite

![image](https://github.com/farm-fe/farm/assets/35885819/e9f896a0-053a-40cd-9fea-f9b117a0b753)
![image](https://github.com/farm-fe/farm/assets/35885819/93ce5f22-d85e-4a7d-9dea-414bdb3b01a1)
import.meta isn't existing global, need any other plugins?

**Comment by wre232114** [comment]
no, just use `import.meta.glob`, it will be compiled during compilation. It does not exist in runtime

**Comment by wre232114** [comment]
see https://farm-fe.github.io/docs/features/script#vite-style-importmetaglob
