### ISSUE TITLE
[Bug] The prefix was incorrectly added to the css property value

### ISSUE THREAD

**Issue by niuiic** [farm-fe/farm#699]
### Steps to reproduce

```
git clone https://github.com/niuiic/gallery
pnpm i
pnpm build
pnpm dev --filter layout
```

Open the browser.

### What is expected?

no prefix be added to `calc(100 * var(--unit-length));`

### What is actually happening?

![image](https://github.com/farm-fe/farm/assets/63799565/2d2b8dbe-7de5-4932-b0e7-57eae54b6b9d)

### System Info

```Shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 10.92 GB / 15.59 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/node
    npm: 9.8.1 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/npm
    pnpm: 8.10.0 - /run/user/1000/fnm_multishells/191835_1698822907518/bin/pnpm
  npmPackages:
    @farmfe/core: ^0.13.16 => 0.13.16 
```
```


### Any additional comments?

_No response_

**Comment by wre232114** [comment]
set `compilation.css.prefixer` to `null`

**Comment by niuiic** [comment]
Doing so will remove all prefixes.

The question is why are attribute values prefixed.

It should have nothing to do with postcss. If I convert px to rem, there's no problem.

**Comment by wre232114** [comment]
The prefixer is supported by `swc css prefixer`, you can turn it off by set `compilation.css.prefixer` to `null` if you don't want to use `swc css prefixer`.

And if you need `postcss prefixer`, add a postcss plugin.

**Comment by niuiic** [comment]
Sorry, I make a mistake. `-webkit-calc` does exist. Long long ago......
