### ISSUE TITLE
[Bug] named exports can not be found after compilation(esm format)

### ISSUE THREAD

**Issue by niuiic** [farm-fe/farm#709]
### Steps to reproduce

```
git clone -b test https://github.com/niuiic/gallery
pnpm i
pnpm build
cd packages/farm-plugins/dist
echo -e "import * as a from './index.mjs'\nconsole.log(a)" > test.mjs
node test.mjs
```

As you methioned before [652](https://github.com/farm-fe/farm/issues/652#issuecomment-1776171295), it's supported. But there may be some bugs when compiling to esm format.

### What is expected?

Something like this. (when compiling to cjs format).

```
[Module: null prototype] {
  FarmRuntimePluginContainer: undefined,
  Module: undefined,
  ModuleSystem: undefined,
  __esModule: true,
  default: { farmRawPlugin: [Getter] },
  farmRawPlugin: [Function: farmRawPlugin]
}
```

### What is actually happening?

```
[Module: null prototype] {  }
```

### System Info

```Shell
System:
    OS: Linux 6.5 Gentoo Linux
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 12.46 GB / 15.36 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /run/user/1000/fnm_multishells/2244_1699183121236/bin/node
    npm: 9.8.0 - /run/user/1000/fnm_multishells/2244_1699183121236/bin/npm
    pnpm: 8.10.2 - /run/user/1000/fnm_multishells/2244_1699183121236/bin/pnpm
```
```


### Any additional comments?

_No response_

**Comment by niuiic** [comment]
Another related bug.

when `partialBundling` is not set, in cjs format
`import {xxx} from 'x'` -> xxx is undefined
`import * as x from 'x'` -> x.xxx is not undefined

- Build the project

```
git clone https://github.com/niuiic/fx-flow
pnpm i
pnpm build
pnpm i
```

- Remove `partialBundling` option in `packages/core/farm.config.cjs.ts`.

- Run test.

```
pnpm test --force
```

- The result.

```
FAIL src/pipe/strict/add.spec.ts
  ● Test suite failed to run

    TypeError: (0 , fx_flow_1.add) is not a function

      2 | import { add } from 'fx-flow'
      3 |
    > 4 | expectType<number>(add(1, 1))
        |                       ^
      5 |
      6 | describe('add', () => {
      7 |   describe('sync', () => {

      at Object.<anonymous> (src/pipe/strict/add.spec.ts:4:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.74 s
Ran all test suites matching /\/home\/niuiic\/Documents\/projects\/node\/fx-flow\/packages\/test\/src\/pipe\/s
trict\/add.spec.ts/i with tests matching "^add sync should be able to calculate the sum of string$".
Test results written to: ../../../../../../../../tmp/nvim.niuiic/QmtNee/2.json

[Terminal closed]
```

**Comment by wre232114** [comment]
I'll take a look

**Comment by niuiic** [comment]
emm, it seems that setting `partialBundling` option does not resolve the problem.

`each.spec.ts` passed, but `pipe.spec.ts` failed. They are same in export way.

**Comment by wre232114** [comment]
`export * from ` in `https://github.com/niuiic/gallery/blob/main/packages/farm-plugins/src/index.ts#L1` is not supported for now. you can use a explicit export like `export { xx } from`

**Comment by wre232114** [comment]
Same here https://github.com/niuiic/fx-flow/blob/main/packages/core/src/pipe/index.ts#L1

**Comment by niuiic** [comment]
> Same here https://github.com/niuiic/fx-flow/blob/main/packages/core/src/pipe/index.ts#L1

This is compiled to cjs. Some exports can be found but some are not.

**Comment by niuiic** [comment]
Ok, I know what happend. It's cache.

Without the option below, some exports cannot be found when compile to `cjs` format.

```
    partialBundling: {
      enforceResources: [
        {
          name: 'index',
          test: ['.+']
        }
      ]
    },
```

**Comment by wre232114** [comment]
`export * from` is support in #710 when `format` is `esm`

**Comment by wre232114** [comment]
> Ok, I know what happend. It's cache.
> 
> Without the option below, some exports cannot be found when compile to `cjs` format.
> 
> ```
>     partialBundling: {
>       enforceResources: [
>         {
>           name: 'index',
>           test: ['.+']
>         }
>       ]
>     },
> ```
> 

`partialBundling` should not affect export infos

**Comment by niuiic** [comment]
That is exactly what I think. But It does affect. You may have a try.

```
git clone https://github.com/niuiic/fx-flow
pnpm initialize
# Remove partialBundling option in packages/core/farm.config.cjs.ts.
pnpm test
# Test failed
# Add partialBundling back
pnpm build --force
pnpm test
# Test passed
```

**Comment by wre232114** [comment]
I'll try

**Comment by wre232114** [comment]
I reproduced this issue, you should set `output.targetEnv` to `node` in the config https://github.com/niuiic/fx-flow/blob/main/packages/core/farm.config.cjs.ts#L10, then it would works

**Comment by niuiic** [comment]
It works.
