### ISSUE TITLE
HMR not working properly in WebStorm

### ISSUE THREAD

**Issue by lopo12123** [farm-fe/farm#739]
### Steps to reproduce

1. run `yarn create farm` to setup template
2. run `yarn dev` to start dev
3. open `src/main.tsx` and modify something, then press `ctrl+s`, but neither the terminal nor the web page changed

### What is expected?

it should trigger hmr when `ctrl+s` is pressed

### What is actually happening?

I tried both 'use in terminal' and 'click to run' to run the development server but it doesn't work in webstorm

use in terminal:
![image](https://github.com/farm-fe/farm/assets/59609929/1cfe81bc-b197-4862-ab49-30d0b024bb19)

click to run
![image](https://github.com/farm-fe/farm/assets/59609929/7df6d641-1ef1-4432-a870-b4a9b59a54a9)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 26.17 GB / 39.68 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
```

### Any additional comments?

my WebStorm info:
![image](https://github.com/farm-fe/farm/assets/59609929/dbf51306-cba6-480b-baea-25bdbb4ea266)

also test in `WebStorm 2023.2.4 Build #WS-232.10203.14, built on October 25, 2023`

**Comment by wre232114** [comment]
I'll take a look.

**Comment by ErKeLost** [comment]
@lopo12123  I have tried to do hot updates on both webstorm 2023.2 and 2023.3.1. You can try to upgrade the version.

![image](https://github.com/farm-fe/farm/assets/66500121/fc540b21-463e-411f-bf24-71e172e4d91d)

**Comment by lopo12123** [comment]
> @lopo12123 I have tried to do hot updates on both webstorm 2023.2 and 2023.3.1. You can try to upgrade the version.
> 
> ![image](https://private-user-images.githubusercontent.com/66500121/292062989-fc540b21-463e-411f-bf24-71e172e4d91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjUyMjgsIm5iZiI6MTcwMzEyNDkyOCwicGF0aCI6Ii82NjUwMDEyMS8yOTIwNjI5ODktZmM1NDBiMjEtNDYzZS00MTFmLWJmMjQtNzFlMTcyZTRkOTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTkzMTA3NDI5YWJlYzRkMjU0MzE2NTEzOTdjZGE1NDVhZGMyNzg0MGY2N2Y5ODhlYWJhNDc0ZjYzMjMwZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CSprAdg0UcXCevnXCOafXNNxw-nQuferka0WIRZNV1E)

i've tried it in 2023.3.1, but it still doesn't work. anyway, i think this may have more to do with my webstorm.
![image](https://github.com/farm-fe/farm/assets/59609929/02d0b675-e714-40e4-8ff1-42988f2eb60b)

**Comment by ErKeLost** [comment]
> > @lopo12123 I have tried to do hot updates on both webstorm 2023.2 and 2023.3.1. You can try to upgrade the version.
> > <img alt="image" width="55.15625" height="21" src="https://private-user-images.githubusercontent.com/66500121/292062989-fc540b21-463e-411f-bf24-71e172e4d91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjUyMjgsIm5iZiI6MTcwMzEyNDkyOCwicGF0aCI6Ii82NjUwMDEyMS8yOTIwNjI5ODktZmM1NDBiMjEtNDYzZS00MTFmLWJmMjQtNzFlMTcyZTRkOTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyMTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTkzMTA3NDI5YWJlYzRkMjU0MzE2NTEzOTdjZGE1NDVhZGMyNzg0MGY2N2Y5ODhlYWJhNDc0ZjYzMjMwZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CSprAdg0UcXCevnXCOafXNNxw-nQuferka0WIRZNV1E">
> 
> i've tried it in 2023.3.1, but it still doesn't work. anyway, i think this may have more to do with my webstorm. ![image](https://private-user-images.githubusercontent.com/59609929/292069786-02d0b675-e714-40e4-8ff1-42988f2eb60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjc2MTUsIm5iZiI6MTcwMzEyNzMxNSwicGF0aCI6Ii81OTYwOTkyOS8yOTIwNjk3ODYtMDJkMGI2NzUtZTcxNC00MGU0LThmZjEtNDI5ODhmMmViNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyNTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZmI4OGI1YzRiYjFiNzU1YjdjNzYxZDMzZTI4YmZjZDg1MGIzMDg0YTVkYmJjMDI3NjgxMzY1NDExNWE4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rk7Aviu0H7w9ovtwJwkpJObKQ9DrOCN8ys-_5NMPHQI)

At first, the hot update failed, but I forgot to check the version, and then my computer redid the system, and then I installed the latest one, or maybe the watcher of farm is not perfect, and we will improve the function of watcher later.

**Comment by ErKeLost** [comment]
The latest version has been changed from watcher to chokidar. You can try again.
