### ISSUE TITLE
[Bug] rust plugin sass(v0.3.1) does not watch scss files imported with `@import` or `@use`

### ISSUE THREAD

**Issue by niuiic** [farm-fe/farm#760]
### Steps to reproduce

```
git clone https://github.com/niuiic/gallery
pnpm i
pnpm dev --filter website
```

Modify `apps/website/src/style/element/adaptation.scss`, set `--unit-length: calc(1rem / 16);` to `--unit-length: calc(1rem / 1);`.

Same to issue #742. I can not reopen it, thus there is a new issue.

### What is expected?

The size of everything on the page becomes very large.

### What is actually happening?

Nothing happened.

Cli doesn't output file change log.

### System Info

```Shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 13.49 GB / 15.59 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /run/user/1000/fnm_multishells/1472_1700530242263/bin/node
    npm: 10.2.0 - /run/user/1000/fnm_multishells/1472_1700530242263/bin/npm
    pnpm: 8.10.5 - /run/user/1000/fnm_multishells/1472_1700530242263/bin/pnpm
  npmPackages:
    @farmfe/core: ^0.14.2 => 0.14.2
```
```


### Any additional comments?

_No response_

**Comment by niuiic** [comment]
I think there is something wrong with cache. Sometimes it works, but sometimes not.

**Comment by wre232114** [comment]
I'll take a look

**Comment by wre232114** [comment]
It does have bug when working with cache and `css modules + @use / @import`, I'll fix it

**Comment by wre232114** [comment]
you can set `persistentCache: false` to it would work as expected
