### ISSUE TITLE
Farm CLI support set env mode and more options

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#762]
### What problem does this feature solve?

like this
https://vitejs.dev/guide/cli.html#options

### What does the proposed API look like?

farm start --mode qa

**Comment by ErKeLost** [comment]
`mode` options we don't support it right now. We may need to specifically consider that most of the other properties are already available.

If you're interested, welcome pr.

**Comment by wre232114** [comment]
Farm's mode can only be `development` or `production`. it does not the same as vite's mode. you may need specify a custom variable like `process.env.CUSTOM_MODE`

**Comment by ErKeLost** [comment]
@YLMC2017  env mode support in v0.14.4
