### ISSUE TITLE
[Bug] HMR not work for imported raw string

### ISSUE THREAD

**Issue by niuiic** [farm-fe/farm#768]
### Steps to reproduce

```
git clone https://github.com/niuiic/gallery
pnpm i
pnpm build
pnpm dev --filter css
```

Open the console and click `wavyUnderline`.

The output:
![image](https://github.com/farm-fe/farm/assets/63799565/6f83ed19-7be3-4928-9a3b-dfceb3a2f1a8)

Edit `packages/css/src/components/wavyUnderline/wavyUnderline.scss`. Delete `color: red;`.

The output:
![image](https://github.com/farm-fe/farm/assets/63799565/690e8902-ed03-4536-9df2-afed3610da7e)

cssStr was not changed, while css was.

`packages/css/src/components/wavyUnderline/index.ts`

```typescript
import css from './wavyUnderline.scss'
import cssStr from './wavyUnderline.scss?raw'

const html = '<span>hello</span>'

console.log(cssStr, 'cssStr')
console.log(css, 'css')

export { css, html }
```

Sass plugin located at `packages/farm-plugins/src/sass.ts`. This scss file is surely added to the watch list.

```typescript
import type { DevServer, JsPlugin, UserConfig } from '@farmfe/core'
import { readFileSync } from 'fs'
import { createRequire } from 'module'

const sassImpl = import(createRequire(import.meta.url).resolve('sass-embedded'))

export const farmSassPlugin = (): JsPlugin => {
  let farmConfig: UserConfig['compilation']
  let devServer: DevServer

  return {
    name: 'farm-sass-plugin',
    config: (args) => (farmConfig = args),
    configDevServer: (args) => (devServer = args),
    load: {
      filters: {
        resolvedPaths: ['\\.scss$', '\\.sass$']
      },
      executor: async (args) => {
        if (args.query.some((x) => x[0] === 'raw')) {
          return {
            content: readFileSync(args.resolvedPath, 'utf8'),
            moduleType: 'sass-raw'
          }
        } else {
          return {
            content: (await sassImpl).compile(args.resolvedPath).css as string,
            moduleType: 'sass-css'
          }
        }
      }
    },
    transform: {
      filters: {
        moduleTypes: ['sass-raw', 'sass-css']
      },
      executor: (args) => {
        if (farmConfig?.mode === 'development') {
          devServer?.addWatchFile(args.resolvedPath, [])
        }

        return { content: 'export default' + '`' + args.content + '`', moduleType: 'js' }
      }
    }
  }
}
```

### What is expected?

cssStr should be changed.

### What is actually happening?

cssStr does not 

### System Info

```Shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 13.33 GB / 15.59 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /run/user/1000/fnm_multishells/11955_1700613217468/bin/node
    npm: 10.2.0 - /run/user/1000/fnm_multishells/11955_1700613217468/bin/npm
    pnpm: 8.10.5 - /run/user/1000/fnm_multishells/11955_1700613217468/bin/pnpm
  npmPackages:
    @farmfe/core: ^0.14.3 => 0.14.3
```
```


### Any additional comments?

_No response_

**Comment by niuiic** [comment]
![image](https://github.com/farm-fe/farm/assets/63799565/84144acd-88e8-4b3c-bebb-e6f32b5fe4f9)

BTW, `Promise<null | undefined>` may be missing.

**Comment by wre232114** [comment]
```ts
 filters: {
        resolvedPaths: ['\\.scss$', '\\.sass$']
      },
```
does not contains query, for example, try `\\.scss(\\?raw)?$`

**Comment by wre232114** [comment]
> BTW, `Promise<null | undefined>` may be missing.
> 
> And some crates required for writing rust plugins are outdated or not published.

I'll add it and publish outdate crates. But for rust plugins, the hooks or internal may be changed before 1.0, this may bring compatible issues when upgrade @farmfe/core without rebuilding custom rust plugins

**Comment by niuiic** [comment]
This does not work. It seems that `resolvedPaths` does not contain query params.

Another plugin `packages/farm-plugins/src/raw.ts` sets this to `['.*']`, did not work either.

I tried, nothing changed.

**Comment by wre232114** [comment]
I'll try

**Comment by wre232114** [comment]
It does not have a bug when working with both `.scss` and `.scss?raw`, I'll fix it. BTW, query is also needed when using resolvedPaths in JS plugins
