### ISSUE TITLE
source map chain is empty

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#770]
### Steps to reproduce

![17006405448641](https://github.com/farm-fe/farm/assets/35885819/f433b7e4-0d75-4698-ae45-e62a39cd955c)

### What is expected?

Build completed

### What is actually happening?

[ Farm ] Using config file at E:\work\my-vue-app\farm.config.js
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\enhanced-magic-string-0.0.11\src\collapse_sourcemap\mod.rs:44:5:     
source map chain is empty
stack backtrace:
   0:     0x7ffabc85d395 - napi_register_module_v1
   1:     0x7ffabc39ff9d - <unknown>
   2:     0x7ffabc843241 - napi_register_module_v1
   3:     0x7ffabc85f7da - napi_register_module_v1
   4:     0x7ffabc85f13f - napi_register_module_v1
   5:     0x7ffabc85fed1 - napi_register_module_v1
   6:     0x7ffabc85f9bb - napi_register_module_v1
   7:     0x7ffabc85f939 - napi_register_module_v1
   8:     0x7ffabc85f924 - napi_register_module_v1
   9:     0x7ffabd043697 - wasmer_vm_imported_memory32_atomic_notify
  10:     0x7ffabc4e2c04 - <unknown>
  11:     0x7ffabc66f637 - farm_create_swc_source_map
  12:     0x7ffabc50b132 - <unknown>
  13:     0x7ffabc5049ca - <unknown>
  14:     0x7ffabc50a1a8 - <unknown>
  15:     0x7ffabc5048e5 - <unknown>
  16:     0x7ffabc50a313 - <unknown>
  17:     0x7ffabc5048e5 - <unknown>
  18:     0x7ffabc50a1a8 - <unknown>
  19:    thread ' <unnamed>0x' panicked at 7ffabc5048e5C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\enhanced-magic-string-0.0.11\src\collapse_sourcemap\mod.rs: - 44<unknown>:
5:
source map chain is empty
  20:     0x7ffabc50a1a8 - <unknown>
  21:     0x7ffabc5048e5 - <unknown>
  22:     0x7ffabc50a1a8 - <unknown>
  23:     0x7ffabc5048e5 - <unknown>
  24:     0x7ffabc4fc60b - <unknown>
  25:     0x7ffabd05eaac - wasmer_vm_imported_memory32_atomic_notify
  26:     0x7ffabc7aa1bb - napi_register_module_v1
  27:     0x7ffabc7a906f - napi_register_module_v1
  28:     0x7ffabc859ebb - napi_register_module_v1
  29:     0x7ffb51c17344 - BaseThreadInitThunk
  30:     0x7ffb533a26b1 - RtlUserThreadStart

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.17 GB / 15.79 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.2 => 0.14.2
```

**Comment by wre232114** [comment]
Could you provide more information to reproduce this issue

**Comment by YLMC2017** [comment]
Is there any way to get full build debug log

**Comment by wre232114** [comment]
you can try https://github.com/farm-fe/farm/tree/main/js-plugins/record-viewer

**Comment by YLMC2017** [comment]
@wre232114 
![image](https://github.com/farm-fe/farm/assets/35885819/9f7b32fb-6e53-472e-9ecd-85c36b68d7d9)
https://www.npmjs.com/package/@farmfe/js-plugin-record-viewer?activeTab=code
package is empty?

**Comment by wre232114** [comment]
I'll republish it. dist files are missing

**Comment by YLMC2017** [comment]
![c1](https://github.com/farm-fe/farm/assets/35885819/3cf6e062-2a06-45e5-8e2a-17d680343505)
![c2](https://github.com/farm-fe/farm/assets/35885819/2c5462e6-a2df-42ff-9609-116668506ca0)

I found the reason, add comment in style tag then run build.

**Comment by YLMC2017** [comment]
https://github.com/YLMC2017/my-vue-app-2

npm run build

The same problem in Linux.

![s1](https://github.com/farm-fe/farm/assets/35885819/6f909df2-0d5c-4715-86a4-be84df879768)

**Comment by YLMC2017** [comment]
https://codesandbox.io/p/github/YLMC2017/my-vue-app-2/draft/mystifying-smoke?file=%2F.devcontainer%2Fdevcontainer.json%3A9%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpj6yy4f0007356jx1qp4lqu%2522%252C%2522sizes%2522%253A%255B56.31319358816276%252C43.68680641183724%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpj6yy4e0003356jyhebzh0j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpj6yy4e0005356jlstn9wjy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpj6yy4e0006356jbf6srv3q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpj6yy4e0003356jyhebzh0j%2522%253A%257B%2522id%2522%253A%2522clpj6yy4e0003356jyhebzh0j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpj79cnj0003356jw8u8n2pl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252F.devcontainer%252Fdevcontainer.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpj79cnj0003356jw8u8n2pl%2522%257D%252C%2522clpj6yy4e0006356jbf6srv3q%2522%253A%257B%2522id%2522%253A%2522clpj6yy4e0006356jbf6srv3q%2522%252C%2522activeTabId%2522%253A%2522clpj750av01a0356jcqmij1ur%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A9001%252C%2522id%2522%253A%2522clpj750av01a0356jcqmij1ur%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Ftest%252Ftest1%252Ftest2%2522%257D%255D%257D%252C%2522clpj6yy4e0005356jlstn9wjy%2522%253A%257B%2522id%2522%253A%2522clpj6yy4e0005356jlstn9wjy%2522%252C%2522activeTabId%2522%253A%2522clpj71lt400j1356jl20i2cbq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpj6yy4e0004356j1yvriegq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpj6yyca000nehhv3njifmam%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clpj719ig00by356jdjhc24vm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520build%2522%252C%2522id%2522%253A%2522clpj71lt400j1356jl20i2cbq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clpj74qq0014u356jeqyfy7xi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D


![q1](https://github.com/farm-fe/farm/assets/35885819/09d2e5f9-6da7-4c81-883c-bd759ee26548)

**Comment by wre232114** [comment]
I don't have permission to visit this project

**Comment by YLMC2017** [comment]
https://codesandbox.io/invite/6r5pp4m3dcdycrhx

**Comment by wre232114** [comment]
thanks, i reproduced it, it will be fixed
