### ISSUE TITLE
Component is missing template or render function.

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#787]
### Steps to reproduce

First cold start ,child page rendered fail 
![b1](https://github.com/farm-fe/farm/assets/35885819/0ed0ad87-e6dd-45dd-8352-5e65b88c22e9)
When full refresh, child page load success
![b2](https://github.com/farm-fe/farm/assets/35885819/2530211f-cc66-4ff9-80c0-53904fefd960)

Reproduce code:
https://github.com/YLMC2017/my-vue-app-2

### What is expected?

The child page render success

### What is actually happening?

Component is missing template or render function.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.25 GB / 15.79 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.7 => 0.14.7
```

**Comment by wre232114** [comment]
I'll try

**Comment by wre232114** [comment]
It can not be produced in macos, I'll try windows tonight

**Comment by YLMC2017** [comment]
![b3](https://github.com/farm-fe/farm/assets/35885819/c8394779-a123-4cdb-8064-678b73d4e813)
Set lazyCompilation: false, the problem can resolved.

**Comment by YLMC2017** [comment]
The same problem as another windows computer
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz     
    Memory: 1.83 GB / 15.94 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @farmfe/core: ^0.14.3 => 0.14.7

I test it in AlmaLinux is work fine.
