### ISSUE TITLE
Can not resolve `data:,` from index.html.

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#794]
### Steps to reproduce

index.html head tag add
<link rel="icon" href="data:," />

### What is expected?

Build Success

### What is actually happening?

 Build failed due to errors:

 Can not resolve `data:,` from index.html.
Original error: None.

Potential Causes:
1.The file that `data:,` points to does not exist.
2.Install it first if `data:,` is an dependency from node_modules, if you are using pnpm refer to [https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here] for solutions.      
3. If `data:,` is a alias, make sure your alias config is correct.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.95 GB / 15.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.8 => 0.14.8
```

**Comment by wre232114** [comment]
fixed in 0.14.10
