### ISSUE TITLE
Assets url error in dev

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#808]
### Steps to reproduce

![l1](https://github.com/farm-fe/farm/assets/35885819/0bd6db68-f169-47c5-ae54-6cab09f9f082)
![l2](https://github.com/farm-fe/farm/assets/35885819/634130ab-083c-46cb-b953-232069cc7efb)

https://github.com/YLMC2017/my-vue-app-2/tree/assets_test2
npm run dev

### What is expected?

Pic loaded

### What is actually happening?

Pic load fail

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.30 GB / 15.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.10 => 0.14.10
```

**Comment by wre232114** [comment]
fixed in 0.14.11
