### ISSUE TITLE
farm-soybean-admin build error Expression expected

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#813]
### Steps to reproduce

![a2](https://github.com/farm-fe/farm/assets/35885819/e91d158b-0cab-4423-9e82-beb7526c37fc)

https://github.com/farm-fe/farm-soybean-admin

update deps

 "@farmfe/cli": "^0.5.11",
  "@farmfe/core": "^0.14.12",
  "@farmfe/js-plugin-postcss": "1.2.0",
  "@farmfe/js-plugin-vue": "^3.2.0",
  "@farmfe/plugin-sass": "^0.3.3",

npm run build:farm

### What is expected?

Build Success

### What is actually happening?

Expression expected

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.23 GB / 15.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.12 => 0.14.12
```

**Comment by wre232114** [comment]
config of this project needs to be updated, I'll update

**Comment by wre232114** [comment]
The project is updated
