### ISSUE TITLE
Constructor Decorators fail to parse

### ISSUE THREAD

**Issue by wSedlacek** [farm-fe/farm#814]
### Steps to reproduce

https://github.com/wSedlacek/farm-node-decorators
Run `pnpm build` and see that it fails to parse.
Change the config to input `working.ts` and see if does build.

Examples were taken from https://www.typescriptlang.org/docs/handbook/decorators.html

### What is expected?

Examples from https://www.typescriptlang.org/docs/handbook/decorators.html should build as expected.

### What is actually happening?

When running `pnpm build` the following error is shown.

```
❯ pnpm build

> @farmfe-examples/node@1.0.0 build /Users/wsedlacek/Code/side/farm-project
> farm build

[ Farm ] Using config file at /Users/wsedlacek/Code/side/farm-project/farm.config.ts
thread '<unnamed>' panicked at crates/plugin_minify/src/lib.rs:57:10:
called `Result::unwrap()` on an `Err` value: ParseError { resolved_path: "main_4ee9", msg: "\n  \u{1b}[38;2;255;30;30m×\u{1b}[0m Unexpected token `@`. Expected yield, an identifier, [ or {\n    ╭─[\u{1b}[38;2;92;157;255;1;4mmain_4ee9\u{1b}[0m:72:1]\n \u{1b}[2m72\u{1b}[0m │             {\n \u{1b}[2m73\u{1b}[0m │                 key: \"print\",\n \u{1b}[2m74\u{1b}[0m │                 value: function print(\n \u{1b}[2m75\u{1b}[0m │                 @required\n    · \u{1b}[38;2;246;87;248m                ─\u{1b}[0m\n \u{1b}[2m76\u{1b}[0m │                 verbose) {\n \u{1b}[2m77\u{1b}[0m │                     if (verbose) {\n \u{1b}[2m78\u{1b}[0m │                         return \"type: \".concat(this.type, \"\\ntitle: \").concat(this.title);\n    ╰────\n" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ELIFECYCLE  Command failed.
fish: Job 1, 'pnpm build' terminated by signal SIGABRT (Abort)
```

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 76.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.1 - /usr/local/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Safari: 16.6
  npmPackages:
    @farmfe/core: ^0.14.12 => 0.14.12
```

### Any additional comments?

When trying to call `build()` programmatically from `@farmfe/core` in this situation this error occurs
```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_compat_es2015-0.1.39/src/classes/constructor.rs:133:22:
not implemented: TsParamProp in constructor
```

I also noticed that the output even when configured for commonjs adds `import` statements for the runtime instead of `require()` resulting in runtime errors even when the build step does work.

**Comment by wSedlacek** [comment]
The repo has this issue as soon as you run the build command.

The broken.ts provides an example of using a param decorator in a constructor. It seems like (based on the other error) that swc cannot translate constructor parameter decorators to es2015 which would be fine IF you could have it transform to es2016 or some other target.

**Comment by wre232114** [comment]
fixed in 0.14.13. i also add a example under examples/decorators for decorators

**Comment by wSedlacek** [comment]
Thank you very much! I will check it out.
It will be a minute before I can check it out.
It looks like you made some changes to the output too. I hope that will address the issue I had with `import` statements.

**Comment by wre232114** [comment]
> I hope that will address the issue I had with import statements.

It will, I reproduced the `import runtime` error, and it has been fixed.
