### ISSUE TITLE
Vue Lazy loading no work, initial page request all chunk

### ISSUE THREAD

**Issue by YLMC2017** [farm-fe/farm#823]
### Steps to reproduce

Farm:
![f1](https://github.com/farm-fe/farm/assets/35885819/88d1c7d7-2f00-4e36-b02c-7b5457d42434)

Compare to Vite:
![f2](https://github.com/farm-fe/farm/assets/35885819/c1cf2d89-ed62-46cd-9da1-0760cb49a378)

### What is expected?

demand loading

https://vuejs.org/guide/best-practices/performance.html#code-splitting

### What is actually happening?

loaded all chunk

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.01 GB / 15.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @farmfe/core: ^0.14.12 => 0.14.12
```

**Comment by YLMC2017** [comment]
Enabled gzip
![f3](https://github.com/farm-fe/farm/assets/35885819/65ec55d8-0ef9-4b0f-8669-858959010b3e)
300kB bigger than rollup

**Comment by wre232114** [comment]
In Farm polyfill is enabled by default, but vite does not. You can set `compilation.presetEnv` to `false` then retry.
