### ISSUE TITLE
✨ [Feature]: Svelte Support

### ISSUE THREAD

**Issue by Bellisario** [farm-fe/farm#825]
### What problem does this feature solve?

Vite has a built-in template for Svelte. Would be great to have it on Farm, too.

### What does the proposed API look like?

- support for `vite-plugin-svelte`
trying to create my own template, Farm throws an error:\
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in [...]/node_modules/@sveltejs/vite-plugin-svelte/package.json`
- create a `svelte` template for `create-farm`

**Comment by baiwusanyu-c** [comment]
It seems that farm did not parse the entry file correctly, but I tried it and found that the svelte official plug-in only provides esm format. Does farm only support cjs format packages?

**Comment by wre232114** [comment]
farm support esm packages, but for `farm.config.ts`, farm will compile it to cjs for compatibility. you can use `farm.config.mjs` with esm format

**Comment by ErKeLost** [comment]
Svelte's vite plugin still needs to adapt in terms of `hmr`, and we will solve this problem as soon as possible.

**Comment by wre232114** [comment]
supported in `@farmfe/core@0.15.6`
