### ISSUE TITLE
unplugin-vue-router

### ISSUE THREAD

**Issue by MinatoHikari** [farm-fe/farm#841]
### Steps to reproduce

follow the plugin install guide, 
set `dts: './typed-router.d.ts',` option.

### What is expected?

successfully start the dev server

### What is actually happening?

run dev failed.

### System Info

```Shell
Vite plugin 'unplugin-vue-router' is not compatible with Farm for now. Because it uses viteModuleGraph['getModuleById'] which is not supported by Farm. Current supported keys are: getModulesByFile,context
```

**Comment by ErKeLost** [comment]
at present, there are some `vite` api that we haven't adapted yet.  we will solve the problem of vite adaptation this month.

**Comment by MinatoHikari** [comment]
> at present, there are some `vite` api that we haven't adapted yet. we will solve the problem of vite adaptation this month.

Fine.

**Comment by wre232114** [comment]
supported in @farmfe/core@0.15.4
