### ISSUE TITLE
[Bug Report]: HMR Failure When Modifying CSS Files

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#855]
### Steps to reproduce

1. `pnpm create farm`
2. choose react template
3. remove `index.css` code ( all code )

### What is expected?

normal

### What is actually happening?

hmr not work

### System Info

```Shell
macos
```

**Comment by wre232114** [comment]
I'll take a look

**Comment by Zcxxxx** [comment]
mark

**Comment by wre232114** [comment]
fixed in 0.15.0
