### ISSUE TITLE
[Bug Report]: Refreshing the page causes network requests and compilation failures to occur occasionally

### ISSUE THREAD

**Issue by ErKeLost** [farm-fe/farm#868]
### Steps to reproduce

`example/react`
`reload page`
- F5

### What is expected?

normal

### What is actually happening?

- compilation failures

![image](https://github.com/farm-fe/farm/assets/66500121/f8496cbc-57f3-4343-8a0f-0ddb87f2c16c)

- network requests failures

![image](https://github.com/farm-fe/farm/assets/66500121/556d4e17-6d81-4bfe-a952-22a04446e208)

### System Info

```Shell
macos
```

**Comment by wre232114** [comment]
fixed in v0.15.2
