### ISSUE TITLE
Is top-level await supported?

### ISSUE THREAD

**Issue by Iced-Sun** [farm-fe/farm#869]
### What problem does this feature solve?

Per [rfc2](https://github.com/farm-fe/rfcs/blob/main/rfcs/002-runtime-module-management/rfc.md#top-level-await-export), it reads that farm has already supported top-level await.

After some experiments, I cannot get it work. Am I missing anything?

Here is a minimal setup:
1. `index.js`
```js
const a = await 1
console.log(a)
```
2. `package.json`
```js
{"type":"module"}
```
3. `farm.config.js`
```js
import { defineConfig } from '@farmfe/core'
export default defineConfig({
        compilation: {
                input: {
                        index: './index.js'
                },
                output: { targetEnv: 'node' }
        }
})
```

`node index.js` works while `node dist/index.js` throws `Unexpected reserved word` at `await`.

### What does the proposed API look like?

N/A

**Comment by wre232114** [comment]
Farm does not support top level await for now

**Comment by wre232114** [comment]
Top level await will be supported in `@farmfe/core@1.1.0`
