### ISSUE TITLE
support farm resolver for postcss-import

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#911]
### What problem does this feature solve?

for postcss plugin like `postcss-import`, it needs context info of `@farmfe/js-plugins-postcss`, e.g. `context.resolve` to resolve farm alias.

### What does the proposed API look like?

inline `postcss-import` into `@farmfe/js-plugins-postcss` like vite:
<img width="677" alt="image" src="https://github.com/farm-fe/farm/assets/8372439/394aa883-0625-4f1a-9dcb-eeba197c2407">

 disabled by default.

```ts
// farm.config.ts
export default defineConfig({
    plugins: [postcss({
        internalPlugins: {
            'postcss-import': true,
        }
    })]
});
```

**Comment by Maidang1** [comment]
I will attempt it, If I have time this week.

**Comment by wre232114** [comment]
Thanks!
