### ISSUE TITLE
HMR websocket port error after the port changes

### ISSUE THREAD

**Issue by skywalker512** [farm-fe/farm#953]
### Steps to reproduce

1. There are two projects, A and B, and the node_modules/.farm/cache folders are both empty.

2. Start the two projects separately (A -> B),  B will use port 9001.

3. SIGINT both projects.

4. Restart project B (which initially used port 9001).

5. GET http://localhost:9000/ returns

```
// Inject during compile time
const port = Number("9001" || 9000);
```

6. After deleting node_modules/.farm/cache of project B, it will function normally.

### What is expected?

N/A

### What is actually happening?

N/A

### System Info

```Shell
N/A
```

**Comment by wre232114** [comment]
It's a bug. `PORT` needs to be a part of the cache key. It will be fixed later today

**Comment by wre232114** [comment]
supported in `@farmfe/core@0.16.5`
