### ISSUE TITLE
After cache different lang attrs will cause "ast not found" when use vite vue plugin to handle sfc src referencing scss "module" files

### ISSUE THREAD

**Issue by skywalker512** [farm-fe/farm#969]
### Steps to reproduce

I don't know if this is a bug, but theoretically it should be supported and in line with the rule of Vue SFC.

There are two Vue files here, they reference the same SCSS "module" file (plain SCSS files have no problem).

HelloWorld.vue
```vue
<template>
  <div :class="$style.a">red</div>
</template>

<style scoped module src="./app.module.scss" lang="scss"></style>
```

HelloWorld2.vue
```vue
<template>
  <div :class="$style.a">red2</div>
</template>

<style scoped module src="./app.module.scss"></style>
```

There is no problem running for the first time, but there will be the following problems after caching.
```
thread '<unnamed>' panicked at crates/plugin_css/src/lib.rs:372:30:
ast not found "/data/co/github/farm-vue-reproduce/apps/sfc-src-scss-cache/src/components/app.module.scss.FARM_CSS_MODULES"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/skywalker512/farm-vue-reproduce/tree/main/apps/sfc-src-scss-cache

### What is expected?

N/A

### What is actually happening?

N/A

### System Info

```Shell
N/A
```

**Comment by wre232114** [comment]
fixed in `@farmfe/core@0.16.7`
