### ISSUE TITLE
[Feature] More intelligent HMR connection creation

### ISSUE THREAD

**Issue by skywalker512** [farm-fe/farm#970]
### What problem does this feature solve?

Sometimes we don't directly connect to the dev server, such as gitpod (Web IDEs), or use tools like whistle for proxy. 

In this case, there are many conditions to consider when creating HMR websockets. (In most cases, the corresponding websocket url should be generated based on the current accessed url.) 

During my use of Vite, I hardly need manual configuration.

However, farm seems to only follow the hostname now, everything else is based on the server configuration.

https://github.com/farm-fe/farm/blob/v0.16.6/packages/runtime-plugin-hmr/src/hmr-client.ts#L8-L16

The protocol seems to be hardcoded (others can be configured through farm.config). If I access the development server using https, due to browser restrictions, I must modify the source code in order to establish a successful connection.

https://github.com/farm-fe/farm/blob/v0.16.6/packages/runtime-plugin-hmr/src/hmr-client.ts#L34

### What does the proposed API look like?

I think in most cases, Vite runs very well.

https://github.com/vitejs/vite/blob/v5.0.12/packages/vite/src/client/client.ts#L24-L68

**Comment by wre232114** [comment]
Yes, Farm may need to fallback to direct connection in this case. We will support it later

**Comment by ErKeLost** [comment]
hi @skywalker512  
I see that in the current ws protocol in farm, only protocol needs to be changed according to the http protocol. Do you mean only include
```javascript
    const socket = new WebSocket(`ws://${host}:${port}${path}`, 'farm_hmr');
   // should be
      const protocol = location.protocol === 'https:' ? 'wss' : 'ws';
      const socket = new WebSocket(`${protocol}://${host}:${port}${path}`, 'farm_hmr')
```

**Comment by skywalker512** [comment]
I think both the port and path need to be automatically detected.

- port: Sometimes, webide will provide a domain like https://3000-xxx.xx.xx:443/xxx, which proxies to port 3000.
- path: In some cases, different projects may be developed in different subdirectories of the same domain. HMR needs to follow the public path setting (vite's base configuration).
