### ISSUE TITLE
loadEnv Api

### ISSUE THREAD

**Issue by MinatoHikari** [farm-fe/farm#995]
### What problem does this feature solve?

Currently I have to install dotenv to load env file in defineConfig
```
defineConfig(() => {
const envConf = config({
        path: resolve(process.cwd(), '.env.local'),
    }).parsed;
    const backend = envConf?.BACKEND_SERVER as string;
})
```
I think farm should provide an api which is similiar to vite's loadEnv.

### What does the proposed API look like?

`const env = loadEnv({ ...options })`

**Comment by wre232114** [comment]
We will export full api in 1.0, including `loadEnv`. 1.0 will be released very soon. You can use `farm start -m local` to custom env file for current version(0.16.x)
